"""Derive the signed carrier module from the pinned integer load domain.

The bounded repair source uses nonnegative integer loads on twelve ports.  The
repair-selected Gram has one exact integer radical: loads equal on every
antipodal pair.  Quotienting the Grothendieck load group by that radical gives
the signed six-coordinate module, without inserting a separate ``Z^6``
carrier.  Its image is dense in the conditional rank-three completion.

At protected total ``S``, the nonnegative source image is the finite set
``sum(abs(z_i)) <= S`` with ``sum(z_i) = S mod 2``.  Its displacement lattice
is the even-sum ``D6`` lattice for every positive total and is already
generated by differences of total-one source states.  This finite-index
lattice remains dense after the repair-Gram embedding.

The exact conditional mean ``T = I - L/60`` descends through the quotient and
is proper-carrier equivariant.  The nonlinear repair kernel does not descend:
an exact total-two counterexample has equal quotient input and unequal
one-step quotient distributions.  Thus this packet derives the static module
and expectation intertwiner, not ordered-history descent, a physical position
readback, or physical translations.  No target or comparison data are read.
"""

from __future__ import annotations

import argparse
import copy
from fractions import Fraction
import hashlib
import itertools
import json
from pathlib import Path
from typing import Any, Mapping, Sequence


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RECEIPT = ROOT / "data/repair_closure/port_load_metric_quotient_receipt.json"
COMPLETION_RECEIPT = ROOT / "data/repair_closure/port_gram_completion_bridge_receipt.json"
ACTION_RECEIPT = ROOT / "data/repair_closure/port_gram_equivariant_action_receipt.json"
REPAIR_RECEIPT = ROOT / "data/repair_closure/bounded_atomic_self_readback_closure_receipt.json"
PORT_REPAIR_RECEIPT = ROOT / "data/repair_closure/port_repair_propagation_bridge_receipt.json"
CARRIER_MANIFEST = ROOT / "tests/fixtures/echosahedral_federation_reference.json"
PRODUCER_PATH = Path(__file__).resolve()
VERIFIER_PATH = ROOT / "oph_fpe/dynamics/verify_port_load_metric_quotient_independent.py"
TEST_PATH = ROOT / "tests/test_port_load_metric_quotient.py"

SCHEMA = "oph.port-load-repair-gram-metric-quotient.v1"
STATUS = (
    "EXACT_INTEGER_LOAD_METRIC_QUOTIENT_AND_MEAN_INTERTWINER_ATTAINED__"
    "PATHWISE_DESCENT_POSITION_SEMANTICS_AND_PHYSICAL_ACTION_OPEN"
)
COMPLETION_SCHEMA = "oph.port-gram-hausdorff-completion-bridge.v1"
ACTION_SCHEMA = "oph.port-gram-equivariant-completion-action.v1"
REPAIR_SCHEMA = "oph.bounded_atomic_self_readback_closure.v1"
PORT_REPAIR_SCHEMA = "oph.port_repair_propagation_bridge_receipt.v1"

Q5 = tuple[Fraction, Fraction]
ZERO: Q5 = (Fraction(0), Fraction(0))

CLAIM_BOUNDARY = (
    "The pinned repair source supplies twelve integer load coordinates. The "
    "integer radical of the repair-selected Gram is exactly the subgroup of "
    "antipodally equal loads, so its metric quotient is canonically the signed "
    "six-coordinate module. This removes the module as an independent "
    "algebraic input. The proper carrier action preserves the quotient, and "
    "the exact conditional mean intertwines with its induced operator. For "
    "the thirty source seams, composing the incidence boundary with the load "
    "quotient has rank six and image exactly the even-sum D6 lattice. Its "
    "direction axes bind to the existing edge30 control ray without making "
    "the seams spatial hops or nonlinear repair updates. For "
    "each positive protected total, differences of admissible source states "
    "generate the even-sum D6 lattice, whose repair-Gram image is dense in the "
    "same conditional three-dimensional completion. A fixed-total state set "
    "itself is finite and is not dense. The full nonlinear repair kernel does "
    "not descend through the quotient; an exact total-two counterexample is "
    "retained. Therefore ordered-history descent, operational position "
    "semantics, adoption of the repair clauses, cofinal gluing, global space, "
    "physical action, scale, prediction, and comparison remain open."
)


class PortLoadQuotientError(RuntimeError):
    """Raised when the load-quotient packet fails closed."""


def _canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("ascii")


def _sha(value: Any) -> str:
    return "sha256:" + hashlib.sha256(_canonical_bytes(value)).hexdigest()


def _raw_pin(path: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    return {
        "path": path.relative_to(ROOT).as_posix(),
        "bytes": len(raw),
        "sha256": "sha256:" + hashlib.sha256(raw).hexdigest(),
    }


def _strict_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise PortLoadQuotientError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def _reject_nonfinite(value: str) -> None:
    raise PortLoadQuotientError(f"non-finite JSON constant is forbidden: {value}")


def load_json_strict(path: Path) -> dict[str, Any]:
    try:
        result = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_strict_object,
            parse_constant=_reject_nonfinite,
        )
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise PortLoadQuotientError(f"cannot load {path}: {error}") from error
    if not isinstance(result, dict):
        raise PortLoadQuotientError(f"{path} is not a JSON object")
    return result


def _validated_self_digest(path: Path, schema: str) -> dict[str, Any]:
    receipt = load_json_strict(path)
    payload = copy.deepcopy(receipt)
    digest = payload.pop("receipt_sha256", None)
    if digest != _sha(payload) or receipt.get("schema") != schema:
        raise PortLoadQuotientError(f"parent contract drifted: {path}")
    return receipt


def _validated_repair() -> dict[str, Any]:
    receipt = load_json_strict(REPAIR_RECEIPT)
    payload = copy.deepcopy(receipt)
    digest = payload.pop("certificate_payload_sha256", None)
    mean = receipt.get("exact_conditional_mean_bridge")
    torsor = receipt.get("directed_seam_torsor")
    if (
        digest != _sha(payload)
        or receipt.get("schema") != REPAIR_SCHEMA
        or receipt.get("scope")
        != "bounded_nonnegative_atomic_loads_on_one_oriented_twelve_port_carrier"
        or not isinstance(mean, Mapping)
        or mean.get("identity")
        != "E[X_next | X=x] = (I - L_icosahedron/60) x"
        or mean.get("all_probed_states_exact_identity_verified") is not True
        or mean.get("full_integer_transition_kernel_is_linear") is not False
        or not isinstance(torsor, Mapping)
        or torsor.get("undirected_seam_count") != 30
        or torsor.get("directed_event_atom_count") != 60
    ):
        raise PortLoadQuotientError("bounded repair source contract drifted")
    return receipt


def _parse_q5(text: str) -> Q5:
    suffix = "*sqrt5"
    if not isinstance(text, str) or not text.endswith(suffix):
        raise PortLoadQuotientError("invalid Q(sqrt5) encoding")
    body = text[: -len(suffix)]
    split = body.find("+", 1)
    if split < 1:
        raise PortLoadQuotientError("invalid Q(sqrt5) split")
    return Fraction(body[:split]), Fraction(body[split + 1 :])


def _parse_control_q5(text: str) -> Q5:
    compact = str(text).replace(" ", "").replace("sqrt(5)", "sqrt5")
    if "*sqrt5" not in compact:
        return Fraction(compact), Fraction()
    body = compact[: -len("*sqrt5")]
    split = body.find("+", 1)
    if split < 1:
        raise PortLoadQuotientError("invalid control Q(sqrt5) encoding")
    return Fraction(body[:split]), Fraction(body[split + 1 :])


def _qtext(value: Q5) -> str:
    def render(item: Fraction) -> str:
        return str(item.numerator) if item.denominator == 1 else f"{item.numerator}/{item.denominator}"

    return f"{render(value[0])}+{render(value[1])}*sqrt5"


def _qadd(left: Q5, right: Q5) -> Q5:
    return left[0] + right[0], left[1] + right[1]


def _qmul(left: Q5, right: Q5) -> Q5:
    return (
        left[0] * right[0] + 5 * left[1] * right[1],
        left[0] * right[1] + left[1] * right[0],
    )


def _qsub(left: Q5, right: Q5) -> Q5:
    return left[0] - right[0], left[1] - right[1]


def _qneg_vector(vector: Sequence[Q5]) -> tuple[Q5, ...]:
    return tuple((-value[0], -value[1]) for value in vector)


def _qaxis(vector: Sequence[Q5]) -> tuple[Q5, ...]:
    frozen = tuple(vector)
    return min(frozen, _qneg_vector(frozen))


def _qlinear_combination(coefficients: Sequence[int], values: Sequence[Q5]) -> Q5:
    result = ZERO
    for coefficient, value in zip(coefficients, values, strict=True):
        result = _qadd(
            result,
            _qmul((Fraction(coefficient), Fraction()), value),
        )
    return result


def _source_gram(completion: Mapping[str, Any]) -> list[list[Q5]]:
    exact = completion.get("exact_repair_selected_gram")
    if not isinstance(exact, Mapping):
        raise PortLoadQuotientError("completion Gram packet absent")
    return [[_parse_q5(value) for value in row] for row in exact["full_gram_qsqrt5"]]


def _source_incidence(completion: Mapping[str, Any]) -> list[list[int]]:
    exact = completion["exact_repair_selected_gram"]
    edges = exact["independent_repair_incidence"]["source_edge_list"]
    adjacency = [[0] * 12 for _ in range(12)]
    for left, right in edges:
        adjacency[left][right] = adjacency[right][left] = 1
    if len(edges) != 30 or any(sum(row) != 5 for row in adjacency):
        raise PortLoadQuotientError("source incidence drifted")
    return adjacency


def _difference_matrix(
    positive: Sequence[int], antipodes: Sequence[int]
) -> list[list[int]]:
    matrix = [[0] * 12 for _ in range(6)]
    for row, port in enumerate(positive):
        matrix[row][port] = 1
        matrix[row][antipodes[port]] = -1
    return matrix


def _matmul(
    left: Sequence[Sequence[Any]], right: Sequence[Sequence[Any]]
) -> list[list[Any]]:
    return [
        [sum((left[i][k] * right[k][j] for k in range(len(right))), 0) for j in range(len(right[0]))]
        for i in range(len(left))
    ]


def _qmatmul(
    left: Sequence[Sequence[Q5]], right: Sequence[Sequence[Q5]]
) -> list[list[Q5]]:
    output = []
    for i in range(len(left)):
        row = []
        for j in range(len(right[0])):
            value = ZERO
            for k in range(len(right)):
                value = _qadd(value, _qmul(left[i][k], right[k][j]))
            row.append(value)
        output.append(row)
    return output


def _transpose(matrix: Sequence[Sequence[Any]]) -> list[list[Any]]:
    return [list(column) for column in zip(*matrix, strict=True)]


def _rational_matrix_product(
    left: Sequence[Sequence[Fraction]], right: Sequence[Sequence[Fraction]]
) -> list[list[Fraction]]:
    return [
        [
            sum((left[i][k] * right[k][j] for k in range(len(right))), Fraction())
            for j in range(len(right[0]))
        ]
        for i in range(len(left))
    ]


def _determinant_integer(matrix: Sequence[Sequence[int]]) -> int:
    work = [[Fraction(value) for value in row] for row in matrix]
    sign = 1
    determinant = Fraction(1)
    for column in range(len(work)):
        pivot = next(
            (row for row in range(column, len(work)) if work[row][column]), None
        )
        if pivot is None:
            return 0
        if pivot != column:
            work[column], work[pivot] = work[pivot], work[column]
            sign *= -1
        diagonal = work[column][column]
        determinant *= diagonal
        for row in range(column + 1, len(work)):
            factor = work[row][column] / diagonal
            for index in range(column, len(work)):
                work[row][index] -= factor * work[column][index]
    value = sign * determinant
    if value.denominator != 1:
        raise PortLoadQuotientError("integer matrix has nonintegral determinant")
    return value.numerator


def _compositions(total: int, slots: int) -> list[tuple[int, ...]]:
    output: list[tuple[int, ...]] = []

    def visit(remaining: int, index: int, row: tuple[int, ...]) -> None:
        if index == slots - 1:
            output.append(row + (remaining,))
            return
        for value in range(remaining + 1):
            visit(remaining - value, index + 1, row + (value,))

    visit(total, 0, ())
    return output


def _apply_difference(matrix: Sequence[Sequence[int]], state: Sequence[int]) -> tuple[int, ...]:
    return tuple(sum(row[index] * state[index] for index in range(12)) for row in matrix)


def _formula_image(total: int) -> set[tuple[int, ...]]:
    return {
        value
        for value in itertools.product(range(-total, total + 1), repeat=6)
        if sum(abs(item) for item in value) <= total
        and (sum(value) - total) % 2 == 0
    }


def _balanced_outcome(state: Sequence[int], left: int, right: int) -> tuple[int, ...]:
    output = list(state)
    total = state[left] + state[right]
    output[left] = total // 2
    output[right] = total - output[left]
    return tuple(output)


def _quotient_distribution(
    state: Sequence[int], edges: Sequence[tuple[int, int]], difference: Sequence[Sequence[int]]
) -> dict[tuple[int, ...], Fraction]:
    output: dict[tuple[int, ...], Fraction] = {}
    for left, right in edges:
        for directed_left, directed_right in ((left, right), (right, left)):
            target = _balanced_outcome(state, directed_left, directed_right)
            quotient = _apply_difference(difference, target)
            output[quotient] = output.get(quotient, Fraction()) + Fraction(1, 60)
    return output


def _distribution_rows(distribution: Mapping[tuple[int, ...], Fraction]) -> list[dict[str, Any]]:
    return [
        {
            "z": list(value),
            "probability": f"{probability.numerator}/{probability.denominator}",
        }
        for value, probability in sorted(distribution.items())
    ]


def _expectation(distribution: Mapping[tuple[int, ...], Fraction]) -> tuple[Fraction, ...]:
    return tuple(
        sum((probability * value[index] for value, probability in distribution.items()), Fraction())
        for index in range(6)
    )


def produce_receipt() -> dict[str, Any]:
    completion = _validated_self_digest(COMPLETION_RECEIPT, COMPLETION_SCHEMA)
    action = _validated_self_digest(ACTION_RECEIPT, ACTION_SCHEMA)
    repair = _validated_repair()
    port_repair = _validated_self_digest(PORT_REPAIR_RECEIPT, PORT_REPAIR_SCHEMA)
    load_json_strict(CARRIER_MANIFEST)
    gram12 = _source_gram(completion)
    exact_module = completion["exact_signed_module_completion"]
    positive = tuple(exact_module["positive_port_basis"])
    relation_rows = exact_module["antipodal_relations"]
    antipodes = list(range(12))
    for left, right in relation_rows:
        antipodes[left] = right
        antipodes[right] = left
    antipodes_tuple = tuple(antipodes)
    difference = _difference_matrix(positive, antipodes_tuple)
    integer_section = [[0] * 6 for _ in range(12)]
    for column, port in enumerate(positive):
        integer_section[port][column] = 1
    if _matmul(difference, integer_section) != [
        [int(row == column) for column in range(6)] for row in range(6)
    ]:
        raise PortLoadQuotientError("load-difference map is not split-surjective")
    gram6 = [[gram12[left][right] for right in positive] for left in positive]

    difference_q5 = [[(Fraction(value), Fraction()) for value in row] for row in difference]
    factorized = _qmatmul(
        _transpose(difference_q5), _qmatmul(gram6, difference_q5)
    )
    if factorized != gram12:
        raise PortLoadQuotientError("load Gram does not factor through antipodal differences")
    if exact_module.get("integer_kernel_is_zero") is not True:
        raise PortLoadQuotientError("parent signed-module integer kernel drifted")

    image_rows = []
    for total in range(5):
        states = _compositions(total, 12)
        observed = {_apply_difference(difference, state) for state in states}
        expected = _formula_image(total)
        if observed != expected:
            raise PortLoadQuotientError(f"fixed-total image formula failed at {total}")
        image_rows.append(
            {
                "protected_total": total,
                "source_state_count": len(states),
                "distinct_quotient_state_count": len(observed),
                "exact_nonnegative_image_formula_verified": True,
            }
        )

    # Total-one source states provide an exact index-two displacement basis:
    # e_i-e_5 for i<5 and 2e_5, using positive and antipodal one-load states.
    d6_basis = [
        [int(column == row) - int(column == 5) for column in range(6)]
        for row in range(5)
    ]
    d6_basis.append([0, 0, 0, 0, 0, 2])
    d6_matrix = _transpose(d6_basis)
    leading_minor_determinants = [
        abs(
            _determinant_integer(
                [row[:size] for row in d6_matrix[:size]]
            )
        )
        for size in range(1, 7)
    ]
    if leading_minor_determinants != [1, 1, 1, 1, 1, 2]:
        raise PortLoadQuotientError("D6 Smith witness drifted")
    # Unit minors through size five and full determinant two give the Smith
    # invariants (1,1,1,1,1,2).
    d6_smith_invariants = leading_minor_determinants
    d6_index = abs(_determinant_integer(d6_matrix))

    adjacency = _source_incidence(completion)
    edges = tuple(
        (left, right)
        for left in range(12)
        for right in range(left + 1, 12)
        if adjacency[left][right]
    )
    seam_boundary = [[0] * len(edges) for _ in range(12)]
    for column, (left, right) in enumerate(edges):
        seam_boundary[left][column] = -1
        seam_boundary[right][column] = 1
    seam_current = _matmul(difference, seam_boundary)
    if not all(sum(seam_current[row][column] for row in range(6)) % 2 == 0 for column in range(30)):
        raise PortLoadQuotientError("a seam current escaped the even-sum lattice")
    seam_minor_columns: tuple[int, ...] | None = None
    seam_minor_determinant = 0
    for columns in itertools.combinations(range(30), 6):
        minor = [[seam_current[row][column] for column in columns] for row in range(6)]
        determinant = _determinant_integer(minor)
        if abs(determinant) == 2:
            seam_minor_columns = tuple(columns)
            seam_minor_determinant = determinant
            break
    if seam_minor_columns is None:
        raise PortLoadQuotientError("no index-two seam-current witness found")

    raw_coordinates = exact_module["raw_generator_coordinates_qsqrt5"]
    source_coordinates: list[tuple[Q5, Q5, Q5] | None] = [None] * 12
    for port, row in zip(positive, raw_coordinates, strict=True):
        source_coordinates[port] = tuple(_parse_q5(value) for value in row)  # type: ignore[assignment]
        source_coordinates[antipodes_tuple[port]] = _qneg_vector(
            source_coordinates[port]  # type: ignore[arg-type]
        )  # type: ignore[assignment]
    if any(value is None for value in source_coordinates):
        raise PortLoadQuotientError("source coordinate chart is incomplete")
    seam_current_coordinates = []
    for column, (left, right) in enumerate(edges):
        chart_row = tuple(
            _qlinear_combination(
                [seam_current[basis][column] for basis in range(6)],
                [
                    source_coordinates[positive[basis]][coordinate]  # type: ignore[index]
                    for basis in range(6)
                ],
            )
            for coordinate in range(3)
        )
        direct_row = tuple(
            _qsub(
                source_coordinates[right][coordinate],  # type: ignore[index]
                source_coordinates[left][coordinate],  # type: ignore[index]
            )
            for coordinate in range(3)
        )
        if chart_row != direct_row:
            raise PortLoadQuotientError("seam current chart does not equal port difference")
        seam_current_coordinates.append(chart_row)
    phi: Q5 = (Fraction(1, 2), Fraction(1, 2))
    seam_direction_axes = sorted(
        _qaxis(
            tuple(
                _qmul(phi, seam_current_coordinates[column][coordinate])
                for coordinate in range(3)
            )
        )
        for column in range(30)
    )
    edge30 = port_repair["exact_orbit_ray_table"]["rows"]["edge30"]
    control_direction_axes = sorted(
        _qaxis(tuple(_parse_control_q5(value) for value in row))
        for row in edge30["directions"]
    )
    if seam_direction_axes != control_direction_axes:
        raise PortLoadQuotientError("seam boundary does not bind to edge30 control axes")

    laplacian = [
        [5 * int(i == j) - adjacency[i][j] for j in range(12)] for i in range(12)
    ]
    t12 = [
        [Fraction(int(i == j)) - Fraction(laplacian[i][j], 60) for j in range(12)]
        for i in range(12)
    ]
    section = [[Fraction()] * 6 for _ in range(12)]
    for column, port in enumerate(positive):
        section[port][column] = Fraction(1)
    difference_fraction = [[Fraction(value) for value in row] for row in difference]
    t6 = _rational_matrix_product(
        _rational_matrix_product(difference_fraction, t12), section
    )
    if _rational_matrix_product(difference_fraction, t12) != _rational_matrix_product(
        t6, difference_fraction
    ):
        raise PortLoadQuotientError("conditional mean does not descend")

    relabel = completion["exact_repair_selected_gram"]["independent_repair_incidence"][
        "fixture_to_source_port_map"
    ]
    inverse_relabel = [0] * 12
    for fixture, source in enumerate(relabel):
        inverse_relabel[source] = fixture
    action_gram = action["exact_completion_action"][
        "selected_Gram_in_manifest_order_qsqrt5"
    ]
    expected_manifest_gram = [
        [_qtext(gram12[relabel[i]][relabel[j]]) for j in range(12)] for i in range(12)
    ]
    if action_gram != expected_manifest_gram:
        raise PortLoadQuotientError("action/completion frame binding drifted")

    state_left = (0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0)
    state_right = (1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0)
    z_left = _apply_difference(difference, state_left)
    z_right = _apply_difference(difference, state_right)
    distribution_left = _quotient_distribution(state_left, edges, difference)
    distribution_right = _quotient_distribution(state_right, edges, difference)
    if (
        sum(state_left) != 2
        or sum(state_right) != 2
        or z_left != z_right
        or distribution_left == distribution_right
        or _expectation(distribution_left) != _expectation(distribution_right)
    ):
        raise PortLoadQuotientError("pathwise descent counterexample drifted")

    receipt: dict[str, Any] = {
        "schema": SCHEMA,
        "status": STATUS,
        "issues": [655, 663, 666],
        "target_data_read": False,
        "comparison_data_read": False,
        "parent_pins": {
            "repair_selected_completion": {
                **_raw_pin(COMPLETION_RECEIPT),
                "schema": completion["schema"],
                "status": completion["status"],
                "receipt_sha256": completion["receipt_sha256"],
            },
            "conditional_equivariant_completion_action": {
                **_raw_pin(ACTION_RECEIPT),
                "schema": action["schema"],
                "status": action["status"],
                "receipt_sha256": action["receipt_sha256"],
            },
            "bounded_integer_load_repair_source": {
                **_raw_pin(REPAIR_RECEIPT),
                "schema": repair["schema"],
                "status": repair["status"],
                "certificate_payload_sha256": repair["certificate_payload_sha256"],
                "undirected_seam_attempt_count": 30,
                "directed_completion_label_count": 60,
            },
            "edge30_orbit_ray_control": {
                **_raw_pin(PORT_REPAIR_RECEIPT),
                "schema": port_repair["schema"],
                "status": port_repair["status"],
                "receipt_sha256": port_repair["receipt_sha256"],
                "selected_spatial_orbit": port_repair["classification"][
                    "selected_spatial_orbit"
                ],
                "spatial_hop_source_certified": port_repair["classification"][
                    "spatial_hop_source_certified"
                ],
            },
            "carrier_manifest": _raw_pin(CARRIER_MANIFEST),
        },
        "exact_integer_load_metric_quotient": {
            "source_load_group_completion": "Grothendieck(N^12)=Z^12",
            "difference_map": "D(x)_i=x[p_i]-x[-p_i]",
            "positive_port_basis": list(positive),
            "antipodal_involution": list(antipodes_tuple),
            "difference_matrix": difference,
            "integer_section_matrix": integer_section,
            "difference_after_section_is_identity": True,
            "difference_map_surjective": True,
            "Gram_factorization": "G12=D^T*G6*D",
            "Gram_factorization_exact": True,
            "integer_metric_kernel": "ker_Z(G12)=ker_Z(D)={x:x_p=x_-p}",
            "integer_metric_kernel_exact": True,
            "quotient_isomorphic_to_Z6": True,
            "signed_module_independent_input_required": False,
            "signed_module_derived_from_source_load_domain": True,
            "real_Gram_radical_equals_integer_kernel_scalar_extension": False,
            "real_Gram_radical_dimension": 9,
            "integer_kernel_rank": 6,
            "extra_real_radical_directions_have_nonzero_integer_points": False,
            "quotient_completion_equals_parent_conditional_completion": True,
        },
        "fixed_total_source_geometry": {
            "exact_formula": (
                "q(N^12 cap {sum x=S})={z in Z^6: sum|z_i|<=S and "
                "sum z_i congruent S mod 2}"
            ),
            "exhaustive_source_rows": image_rows,
            "unrestricted_integer_fixed_total_image": (
                "q(Z^12 cap {sum x=S})={z in Z^6: sum z_i congruent S mod 2}"
            ),
            "one_fixed_total_nonnegative_image_is_finite": True,
            "one_fixed_total_nonnegative_image_is_dense": False,
            "positive_total_pairwise_displacement_generated_subgroup": (
                "D6={d in Z^6: sum d_i even}"
            ),
            "raw_pairwise_displacement_set_at_fixed_total_is_finite": True,
            "total_one_difference_basis": d6_basis,
            "total_one_difference_basis_matrix": d6_matrix,
            "leading_unit_minor_and_full_determinant_witness": (
                leading_minor_determinants
            ),
            "displacement_lattice_index_in_Z6": d6_index,
            "displacement_lattice_Smith_invariants": d6_smith_invariants,
            "total_one_basis_extends_to_every_positive_total_by_common_filler": True,
            "D6_contains_2Z6": True,
            "D6_repair_Gram_image_dense_in_parent_completion": True,
            "density_uses_displacement_group_completion_not_finite_state_set": True,
        },
        "exact_seam_current_boundary": {
            "oriented_edge_convention": "one column e_right-e_left for each left<right seam",
            "undirected_seam_count": len(edges),
            "source_edges": [list(edge) for edge in edges],
            "boundary_matrix_12_by_30": seam_boundary,
            "signed_seam_current_matrix_D_after_boundary": seam_current,
            "every_seam_current_has_even_coordinate_sum": True,
            "rank": 6,
            "index_two_minor_columns": list(seam_minor_columns),
            "index_two_minor_edges": [list(edges[index]) for index in seam_minor_columns],
            "index_two_minor_determinant": seam_minor_determinant,
            "image_equals_pairwise_displacement_generated_D6": True,
            "Smith_invariants": [1, 1, 1, 1, 1, 2],
            "thirty_seams_are_sixty_or_twelve_translation_events": False,
            "seam_boundary_columns_are_algebraic_load_currents": True,
            "seam_boundary_columns_are_nonlinear_repair_updates": False,
            "D_boundary_chart_equals_port_coordinate_difference_exact": True,
            "edge30_control_axis_multiset_binding_exact": True,
            "edge30_coordinate_chart_scale": "phi=(1+sqrt5)/2",
            "edge30_orientation_signs_selected": False,
            "edge30_control_ray": copy.deepcopy(edge30["ray"]),
            "edge30_control_ray_physicalized": False,
            "edge30_control_ray_digest": _sha(edge30),
            "spatial_hop_source_certified": False,
        },
        "exact_mean_quotient_intertwiner": {
            "source_operator": "T12=I-L_icosahedron/60",
            "induced_operator_q": [
                [f"{value.numerator}/{value.denominator}" for value in row]
                for row in t6
            ],
            "identity": "D*T12=T6*D",
            "identity_exact": True,
            "same_operator_as_parent_response_step": True,
            "proper_carrier_equivariant": True,
            "mean_readback_only": True,
            "unitary_or_physical_propagation_identified": False,
        },
        "pathwise_descent_counterexample": {
            "protected_total": 2,
            "state_left": list(state_left),
            "state_right": list(state_right),
            "same_input_quotient": list(z_left),
            "left_quotient_distribution": _distribution_rows(distribution_left),
            "right_quotient_distribution": _distribution_rows(distribution_right),
            "one_step_quotient_distributions_equal": False,
            "quotient_expectations_equal": True,
            "full_nonlinear_repair_kernel_descends": False,
            "individual_seam_events_are_translation_generators": False,
            "thirty_seam_attempts_identified_with_six_axis_steps": False,
            "sixty_completion_labels_identified_with_twelve_translations": False,
        },
        "attainment": {
            "source_integer_load_metric_quotient_to_signed_module_derived": True,
            "conditional_mean_descends_and_is_equivariant": True,
            "conditional_completion_action_available": True,
            "signed_module_remains_arbitrary_algebraic_control": False,
            "full_pathwise_repair_descent_proved": False,
            "ordered_history_to_position_descent_proved": False,
            "operational_position_readback_selected": False,
            "repair_amendment_adopted": False,
            "cofinal_refinement_gluing_proved": False,
            "physical_translation_action_promoted": False,
            "global_space_promoted": False,
            "physical_prediction_promoted": False,
            "comparison_permitted": False,
        },
        "claim_boundary": CLAIM_BOUNDARY,
        "implementation_pins": [
            _raw_pin(PRODUCER_PATH),
            _raw_pin(VERIFIER_PATH),
            _raw_pin(TEST_PATH),
        ],
    }
    receipt["receipt_sha256"] = _sha(receipt)
    return receipt


def verify_receipt(receipt: Mapping[str, Any]) -> dict[str, bool]:
    expected = produce_receipt()
    if _canonical_bytes(receipt) != _canonical_bytes(expected):
        raise PortLoadQuotientError("receipt does not match exact replay")
    return {
        "receipt": True,
        "integer_metric_quotient": True,
        "dense_displacement_completion": True,
        "mean_intertwiner": True,
        "pathwise_descent": False,
        "physical_position": False,
        "comparison_permitted": False,
    }


def write_receipt(path: Path = DEFAULT_RECEIPT) -> dict[str, Any]:
    receipt = produce_receipt()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return receipt


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_RECEIPT)
    parser.add_argument("--verify", type=Path)
    args = parser.parse_args()
    if args.verify is not None:
        verify_receipt(load_json_strict(args.verify))
        print("PORT_LOAD_METRIC_QUOTIENT_VALID")
        return
    write_receipt(args.output)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
