"""Pole-residue readback of the propagated screen response (issue #569).

The simulator's local channel is the unitary one-step map generated by the
icosahedral coupling.  This module measures the two-point response of that
channel from propagated impulse states, extracts its pole structure, and
reconstructs the residues on the exact Z[sqrt5] lattice with fail-closed
tolerance and uniqueness gates.  The measured statements:

* the response has exactly four pole clusters, whose reconstructed exact
  locations are the Laplacian band costs 0, 5 - sqrt5, 6, 5 + sqrt5 with
  multiplicities 1, 3, 3, 5;
* the residue at the minimal positive pole has measured rank exactly three
  and reconstructs exactly to the frame-band projector: the measured family
  fiber is the slowest-relaxing nonconstant mode of the propagated dynamics;
* the reconstructed residue is primitive (it equals one exact band
  projector), its rotation action is faithful (kernel order one over the
  sixty incidence automorphisms), and Galois conjugation carries it to the
  kernel-band residue at the maximal pole.

CLAIM BOUNDARY.  This is the pole-residue object of the response resolvent
of the propagated screen dynamics, realized inside the screen coefficient
space.  It is not a matter-pole measurement: chirality and spin data, the
matter-pole identification, and laboratory current attachment are open on
issue #569.  External multiplicity copies remain invisible to the screen
response; that boundary is the #617 theorem and is restated here, not
defeated.  The artifact stores exact reconstructed values and booleans
only; no floating-point number enters the payload.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from fractions import Fraction
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np

from oph_fpe.core.charged_response import (
    ChargedResponseError,
    Q5,
    _require,
    canonical_sha256,
    graph_isomorphism,
    incidence_automorphisms,
    isotypic_projectors,
    load_carrier,
)
from oph_fpe.core.echosahedral_dynamics import (
    LocalRecurrentCarrierState,
    propagate_local_recurrent_carriers,
    reference_icosahedral_coupling,
)
import oph_fpe.core.echosahedral_dynamics as _dynamics_module

ARTIFACT_SCHEMA = "oph.charged_response_pole_residue.v1"

PORTS = 12
INTRINSIC_STEP = 0.25
SERIES_STEPS = 8
CHANNEL_TOLERANCE = 1.0e-9
RECONSTRUCTION_TOLERANCE = 1.0e-6
RECONSTRUCTION_MARGIN = 1.0e-3
COEFFICIENT_BOUND = 15
RESIDUE_SCALE = 120

SQRT5 = math.sqrt(5.0)

EXPECTED_POLES: dict[str, Q5] = {
    "unit": Q5.of(0),
    "frame": Q5.of(5, -1),
    "quintet": Q5.of(6),
    "kernel": Q5.of(5, 1),
}

EXPECTED_MULTIPLICITIES = {"unit": 1, "frame": 3, "quintet": 5, "kernel": 3}


def measure_response_series(
    steps: int = SERIES_STEPS, intrinsic_step: float = INTRINSIC_STEP
) -> list[np.ndarray]:
    """Propagate the twelve impulse states and record the measured two-point
    response matrices G(t) with columns U^t e_j."""

    _require(steps >= 2, "SERIES_LENGTH", "at least two steps are required")
    amplitudes = np.eye(PORTS, dtype=np.complex128)
    state = LocalRecurrentCarrierState(
        amplitudes=amplitudes, intrinsic_phase=np.zeros(PORTS, dtype=float)
    )
    series = [state.amplitudes.T.copy()]
    for _ in range(steps):
        state = propagate_local_recurrent_carriers(
            state, intrinsic_step=intrinsic_step
        )
        series.append(state.amplitudes.T.copy())
    return series


def verify_channel_consistency(series: Sequence[np.ndarray]) -> None:
    """The measured series must be the powers of one unitary channel step."""

    _require(
        len(series) >= 3,
        "CHANNEL_CONSISTENCY",
        "the series is too short to verify the one-step channel property",
    )
    _require(
        float(np.max(np.abs(series[0] - np.eye(PORTS)))) <= CHANNEL_TOLERANCE,
        "CHANNEL_CONSISTENCY",
        "the series does not start at the identity impulse configuration",
    )
    step = series[1]
    deviation = float(np.max(np.abs(step.conj().T @ step - np.eye(PORTS))))
    _require(
        deviation <= 1.0e-8,
        "CHANNEL_CONSISTENCY",
        "the measured one-step map is not unitary at tolerance",
    )
    power = np.eye(PORTS, dtype=np.complex128)
    for index, sample in enumerate(series):
        _require(
            float(np.max(np.abs(sample - power))) <= 1.0e-8 * max(index, 1),
            "CHANNEL_CONSISTENCY",
            f"the measured series deviates from the channel powers at step {index}",
        )
        power = power @ step


def reconstruct_q5(value: float, scale: int) -> Q5:
    """Reconstruct ``value`` as (a + b*sqrt5)/scale with integer a, b.

    Fails closed unless exactly one lattice point within the coefficient
    bound sits inside the reconstruction tolerance and every other
    candidate is separated by the declared margin.
    """

    target = value * scale
    candidates: list[tuple[float, int, int]] = []
    for b in range(-COEFFICIENT_BOUND, COEFFICIENT_BOUND + 1):
        a = round(target - b * SQRT5)
        residual = abs(target - a - b * SQRT5)
        candidates.append((residual, int(a), b))
    candidates.sort()
    best_residual, a, b = candidates[0]
    _require(
        best_residual <= RECONSTRUCTION_TOLERANCE * scale,
        "LATTICE_RECONSTRUCTION",
        "a measured value does not sit on the exact lattice at tolerance",
    )
    _require(
        len(candidates) == 1 or candidates[1][0] >= RECONSTRUCTION_MARGIN,
        "LATTICE_RECONSTRUCTION",
        "a measured value is ambiguous on the exact lattice",
    )
    return Q5.of(Fraction(a, scale), Fraction(b, scale))


def extract_pole_residues(
    series: Sequence[np.ndarray], intrinsic_step: float = INTRINSIC_STEP
) -> dict[str, Any]:
    """Extract poles and exact residues from the measured one-step map."""

    verify_channel_consistency(series)
    step = series[1]
    eigenvalues, eigenvectors = np.linalg.eig(step)
    phases = np.angle(eigenvalues)
    generator_values = -phases / intrinsic_step

    order = np.argsort(generator_values)
    generator_values = generator_values[order]
    eigenvectors = eigenvectors[:, order]

    clusters: list[dict[str, Any]] = []
    start = 0
    for index in range(1, len(generator_values) + 1):
        if (
            index == len(generator_values)
            or generator_values[index] - generator_values[index - 1] > 1.0e-6
        ):
            members = slice(start, index)
            vectors = eigenvectors[:, members]
            gram = vectors.conj().T @ vectors
            projector_num = vectors @ np.linalg.inv(gram) @ vectors.conj().T
            clusters.append(
                {
                    "pole_float": float(np.mean(generator_values[members])),
                    "multiplicity": index - start,
                    "projector_float": projector_num,
                }
            )
            start = index
    _require(
        len(clusters) == 4,
        "POLE_COUNT",
        f"the measured response must have exactly four pole clusters, found {len(clusters)}",
    )

    named: dict[str, dict[str, Any]] = {}
    used: set[str] = set()
    for cluster in clusters:
        pole_exact = reconstruct_q5(cluster["pole_float"], 1)
        matched = None
        for band, expected in EXPECTED_POLES.items():
            if band not in used and (pole_exact - expected).is_zero():
                matched = band
                break
        _require(
            matched is not None,
            "POLE_VALUES",
            "a measured pole does not reconstruct to a Laplacian band cost",
        )
        used.add(matched)
        _require(
            cluster["multiplicity"] == EXPECTED_MULTIPLICITIES[matched],
            "POLE_MULTIPLICITY",
            f"the {matched} pole has the wrong measured multiplicity",
        )
        projector_exact = [
            [
                reconstruct_q5(
                    float(np.real(cluster["projector_float"][i][j])), RESIDUE_SCALE
                )
                for j in range(PORTS)
            ]
            for i in range(PORTS)
        ]
        imag_max = float(np.max(np.abs(np.imag(cluster["projector_float"]))))
        _require(
            imag_max <= RECONSTRUCTION_TOLERANCE,
            "RESIDUE_REALITY",
            "a measured residue has a nonreal part beyond tolerance",
        )
        named[matched] = {
            "pole_exact": pole_exact,
            "multiplicity": cluster["multiplicity"],
            "projector_exact": projector_exact,
        }
    return named


def measured_in_carrier_order(carrier: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Measure the pole residues and transport them to the carrier labeling.

    The propagated runtime carries its own port labeling; the measured
    residues are transported through the incidence isomorphism.  Every
    compared residue is invariant under the full automorphism group, so the
    transport does not depend on which isomorphism the search returns.
    """

    series = measure_response_series()
    measured_runtime = extract_pole_residues(series)

    coupling = reference_icosahedral_coupling()
    runtime_graph = [
        [1 if (i != j and float(coupling[i][j]) != 0.0) else 0 for j in range(PORTS)]
        for i in range(PORTS)
    ]
    binding = graph_isomorphism(carrier["adjacency"], runtime_graph)
    _require(
        binding is not None,
        "RUNTIME_ISOMORPHISM",
        "the runtime coupling graph is not isomorphic to the bound carrier incidence",
    )
    measured: dict[str, dict[str, Any]] = {}
    for band, payload in measured_runtime.items():
        runtime_projector = payload["projector_exact"]
        measured[band] = {
            "pole_exact": payload["pole_exact"],
            "multiplicity": payload["multiplicity"],
            "projector_exact": [
                [runtime_projector[binding[i]][binding[j]] for j in range(PORTS)]
                for i in range(PORTS)
            ],
        }
    return measured


def certify_pole_residue_readback(carrier: Mapping[str, Any]) -> dict[str, Any]:
    """Run the measurement and bind it to the exact isotypic structure."""

    measured = measured_in_carrier_order(carrier)

    exact_projectors = isotypic_projectors(carrier["adjacency"])
    for band, payload in measured.items():
        exact = exact_projectors[band]
        recon = payload["projector_exact"]
        _require(
            all(
                (recon[i][j] - exact[i][j]).is_zero()
                for i in range(PORTS)
                for j in range(PORTS)
            ),
            "RESIDUE_EXACT",
            f"the measured {band} residue does not equal the exact band projector",
        )

    ordered = sorted(measured.items(), key=lambda item: item[1]["pole_exact"].to_float())
    _require(
        [name for name, _ in ordered] == ["unit", "frame", "quintet", "kernel"],
        "POLE_ORDER",
        "the measured pole order must be unit < frame < quintet < kernel",
    )
    minimal_positive = ordered[1]
    _require(
        minimal_positive[0] == "frame" and minimal_positive[1]["multiplicity"] == 3,
        "FAMILY_BAND_POLE",
        "the minimal positive measured pole must carry the rank-three frame residue",
    )

    automorphisms = incidence_automorphisms(carrier["adjacency"])
    _require(
        len(automorphisms) == 120,
        "AUTOMORPHISM_COUNT",
        "the incidence automorphism count must be one hundred twenty",
    )
    frame = measured["frame"]["projector_exact"]
    trivial = 0
    rotations = 0
    for permutation in automorphisms:
        moved = [[frame[permutation[i]][j] for j in range(PORTS)] for i in range(PORTS)]
        fixed_rows = all(
            (moved[i][j] - frame[i][j]).is_zero()
            for i in range(PORTS)
            for j in range(PORTS)
        )
        conjugated = [
            [frame[permutation[i]][permutation[j]] for j in range(PORTS)]
            for i in range(PORTS)
        ]
        if all(
            (conjugated[i][j] - frame[i][j]).is_zero()
            for i in range(PORTS)
            for j in range(PORTS)
        ):
            rotations += 1
        if fixed_rows:
            trivial += 1
    _require(
        trivial == 1,
        "FAITHFUL_ACTION",
        "the measured frame residue action must have kernel order one",
    )
    _require(
        rotations == 120,
        "RESIDUE_EQUIVARIANCE",
        "the measured frame residue must be invariant under every incidence automorphism",
    )

    galois = [
        [measured["frame"]["projector_exact"][i][j].conj() for j in range(PORTS)]
        for i in range(PORTS)
    ]
    kernel = measured["kernel"]["projector_exact"]
    _require(
        all(
            (galois[i][j] - kernel[i][j]).is_zero()
            for i in range(PORTS)
            for j in range(PORTS)
        ),
        "GALOIS_RESIDUE_PAIR",
        "conjugation must carry the measured frame residue to the kernel residue",
    )

    return {
        "measured_poles": {
            name: {
                "pole": payload["pole_exact"].render(),
                "multiplicity": payload["multiplicity"],
            }
            for name, payload in measured.items()
        },
        "pole_order": "0 < 5 - sqrt5 < 6 < 5 + sqrt5",
        "family_band_residue": {
            "band": "frame",
            "measured_rank": 3,
            "equals_exact_frame_projector": True,
            "slowest_relaxing_nonconstant_mode": True,
            "faithful_kernel_order": 1,
            "equivariant_under_all_automorphisms": True,
            "galois_partner_at_maximal_pole": True,
        },
        "series": {
            "steps": SERIES_STEPS,
            "intrinsic_step": str(Fraction(INTRINSIC_STEP).limit_denominator(64)),
            "channel_tolerance": str(CHANNEL_TOLERANCE),
            "reconstruction_tolerance": str(RECONSTRUCTION_TOLERANCE),
            "reconstruction_margin": str(RECONSTRUCTION_MARGIN),
            "coefficient_bound": COEFFICIENT_BOUND,
            "residue_scale": RESIDUE_SCALE,
        },
    }


# ---------------------------------------------------------------------------
# Fail-closed controls
# ---------------------------------------------------------------------------


def control_truncated_series() -> dict[str, Any]:
    """A series too short to verify the channel property must refuse."""

    series = measure_response_series()[:2]
    try:
        extract_pole_residues(series)
    except ChargedResponseError as error:
        return {
            "expected_failure": True,
            "failed": True,
            "code": error.code,
        }
    return {"expected_failure": True, "failed": False}


def control_doctored_step() -> dict[str, Any]:
    """A perturbed one-step map must fail lattice reconstruction or the
    exactness gates; a silent pass is forbidden."""

    series = measure_response_series()
    doctored = [sample.copy() for sample in series]
    doctored[1][0, 0] += 1.0e-3
    try:
        extract_pole_residues(doctored)
    except ChargedResponseError as error:
        return {
            "expected_failure": True,
            "failed": True,
            "code": error.code,
        }
    return {"expected_failure": True, "failed": False}


def control_lattice_near_miss() -> dict[str, Any]:
    """A value near, but off, the exact lattice must be refused rather than
    rounded."""

    off_lattice = (10.0 + 2.0 * SQRT5) / RESIDUE_SCALE + 20.0 * RECONSTRUCTION_TOLERANCE
    try:
        reconstruct_q5(off_lattice, RESIDUE_SCALE)
    except ChargedResponseError as error:
        return {
            "expected_failure": True,
            "failed": True,
            "code": error.code,
        }
    return {"expected_failure": True, "failed": False}


def control_swapped_residues(carrier: Mapping[str, Any]) -> dict[str, Any]:
    """Swapping the frame and kernel residues must be detected by the
    exactness gate as the Galois partner."""

    exact = isotypic_projectors(carrier["adjacency"])
    measured = measured_in_carrier_order(carrier)
    swapped = measured["kernel"]["projector_exact"]
    matches_frame = all(
        (swapped[i][j] - exact["frame"][i][j]).is_zero()
        for i in range(PORTS)
        for j in range(PORTS)
    )
    try:
        _require(
            matches_frame,
            "RESIDUE_SWAP_DETECTED",
            "the kernel residue is not the frame projector",
        )
    except ChargedResponseError as error:
        return {
            "expected_failure": True,
            "failed": True,
            "code": error.code,
        }
    return {"expected_failure": True, "failed": False}


# ---------------------------------------------------------------------------
# Artifact assembly
# ---------------------------------------------------------------------------


def _module_sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def produce_pole_residue_artifact(
    carrier_manifest: Mapping[str, Any], parent_artifact: Mapping[str, Any]
) -> dict[str, Any]:
    carrier = load_carrier(carrier_manifest)
    carrier_sha = canonical_sha256(dict(carrier_manifest))
    _require(
        parent_artifact["carrier_binding"]["carrier_manifest_sha256"] == carrier_sha,
        "PARENT_CARRIER",
        "the parent response artifact must bind the same carrier manifest",
    )

    readback = certify_pole_residue_readback(carrier)
    controls = {
        "truncated_series": control_truncated_series(),
        "doctored_step": control_doctored_step(),
        "lattice_near_miss": control_lattice_near_miss(),
        "swapped_residues": control_swapped_residues(carrier),
    }
    for name, verdict in controls.items():
        _require(
            verdict["expected_failure"] is True and verdict["failed"] is True,
            "CONTROL_NOT_FAILED",
            f"control {name} did not record its required failure",
        )

    payload: dict[str, Any] = {
        "schema": ARTIFACT_SCHEMA,
        "issue": 569,
        "claim_boundary": (
            "Measured pole-residue object of the response resolvent of the "
            "propagated screen dynamics, realized inside the screen "
            "coefficient space: four pole clusters at the exact band costs, "
            "with the rank-three frame residue at the minimal positive pole. "
            "This is not a matter-pole measurement; chirality and spin data, "
            "matter-pole identification, and laboratory attachment are open. "
            "External multiplicity copies remain invisible to the screen "
            "response per the standing invisibility theorem."
        ),
        "carrier_binding": {
            "carrier_manifest_sha256": carrier_sha,
            "parent_artifact_sha256": parent_artifact["artifact_sha256"],
        },
        "dynamics_binding": {
            "dynamics_module": "oph_fpe.core.echosahedral_dynamics",
            "dynamics_sha256": _module_sha256(Path(_dynamics_module.__file__)),
            "generator": "icosahedral coupling (the graph Laplacian) under the unitary one-step channel",
        },
        "pole_residue_readback": readback,
        "controls": controls,
    }
    payload["artifact_sha256"] = "sha256:" + canonical_sha256(payload)
    return payload


def write_pole_residue_artifact(
    carrier_manifest_path: Path, parent_artifact_path: Path, output_path: Path
) -> dict[str, Any]:
    manifest = json.loads(carrier_manifest_path.read_text(encoding="utf-8"))
    parent = json.loads(parent_artifact_path.read_text(encoding="utf-8"))
    artifact = produce_pole_residue_artifact(manifest, parent)
    output_path.write_text(
        json.dumps(artifact, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return artifact


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--carrier-manifest", type=Path, required=True)
    parser.add_argument("--parent-artifact", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    artifact = write_pole_residue_artifact(
        args.carrier_manifest, args.parent_artifact, args.out
    )
    print(
        json.dumps(
            {
                "artifact_sha256": artifact["artifact_sha256"],
                "family_band_residue": artifact["pole_residue_readback"][
                    "family_band_residue"
                ],
            },
            indent=2,
        )
    )
    return 0


__all__ = [
    "ARTIFACT_SCHEMA",
    "certify_pole_residue_readback",
    "extract_pole_residues",
    "measure_response_series",
    "produce_pole_residue_artifact",
    "reconstruct_q5",
    "write_pole_residue_artifact",
]


if __name__ == "__main__":
    raise SystemExit(main())
