"""Exact control against identifying seam repair with a port-current algebra.

The scalar A2 seam law supplies thirty conditional equalizers

    E_e = I - (1/2) b_e b_e^T

on the twelve port readings.  Every ``b_e`` has coordinate sum zero, so the
disagreement generators ``G_e = 2(I-E_e) = b_e b_e^T`` act on the
eleven-dimensional zero-sum space ``V_0``.

This module computes three target-independent closure facts:

* the nonzero first commutators ``[G_e,G_f]`` span dimension 49;
* their Lie closure is the full metric-skew algebra ``so(V_0)``, dimension 55;
* the unital operator algebra generated by the equalizers is
  ``End(V_0)``, dimension 121.

All matrices are integral in the fixed basis ``e_i-e_11``.  Ranks are checked
by exact rational elimination and independently modulo two declared primes.
The dimension-55 identification also has a structural upper bound because
every commutator is skew for the positive Gram matrix of that basis.

The result is a negative control on one proposed bridge, not a negative result
about OPH.  It excludes relabeling the scalar repair equalizers as the desired
twelve-dimensional compact current.  A separate reversible-response and
same-current holonomy producer remains necessary.
"""

from __future__ import annotations

import argparse
import copy
from fractions import Fraction
import hashlib
import json
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from oph_fpe.dynamics.self_readback_repair_closure import (
    ORIENTED_BASE_FACES,
    PORT_COUNT,
    exact_reference_edges,
)


SCHEMA = "oph.seam-equalizer-current-control/1.0.0"
STATUS = "ATTAINED_NEGATIVE_CONTROL"
ZERO_SUM_DIMENSION = PORT_COUNT - 1
RANK_PRIMES = (1_000_003, 1_000_033)

Matrix = tuple[tuple[int, ...], ...]


def _canonical_bytes(value: Mapping[str, Any] | Sequence[Any]) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("ascii")


def _sha256(value: Mapping[str, Any] | Sequence[Any]) -> str:
    return "sha256:" + hashlib.sha256(_canonical_bytes(value)).hexdigest()


def _identity(dimension: int) -> Matrix:
    return tuple(
        tuple(int(row == column) for column in range(dimension))
        for row in range(dimension)
    )


def _transpose(matrix: Matrix) -> Matrix:
    return tuple(
        tuple(matrix[row][column] for row in range(len(matrix)))
        for column in range(len(matrix[0]))
    )


def _matrix_add(left: Matrix, right: Matrix) -> Matrix:
    return tuple(
        tuple(
            left[row][column] + right[row][column]
            for column in range(len(left[0]))
        )
        for row in range(len(left))
    )


def _matrix_subtract(left: Matrix, right: Matrix) -> Matrix:
    return tuple(
        tuple(
            left[row][column] - right[row][column]
            for column in range(len(left[0]))
        )
        for row in range(len(left))
    )


def _matrix_multiply(left: Matrix, right: Matrix) -> Matrix:
    inner = len(right)
    return tuple(
        tuple(
            sum(
                left[row][index] * right[index][column]
                for index in range(inner)
            )
            for column in range(len(right[0]))
        )
        for row in range(len(left))
    )


def _commutator(left: Matrix, right: Matrix) -> Matrix:
    return _matrix_subtract(
        _matrix_multiply(left, right),
        _matrix_multiply(right, left),
    )


def _flatten(matrix: Matrix) -> tuple[int, ...]:
    return tuple(entry for row in matrix for entry in row)


def _is_zero(matrix: Matrix) -> bool:
    return not any(_flatten(matrix))


def zero_sum_basis() -> Matrix:
    """Return the columns ``e_0-e_11, ..., e_10-e_11``."""

    return tuple(
        tuple(
            int(row == column) - int(row == ZERO_SUM_DIMENSION)
            for column in range(ZERO_SUM_DIMENSION)
        )
        for row in range(PORT_COUNT)
    )


def zero_sum_gram_matrix() -> Matrix:
    """Return the positive Gram matrix of :func:`zero_sum_basis`."""

    basis = zero_sum_basis()
    return _matrix_multiply(_transpose(basis), basis)


def _restrict_zero_sum(full_operator: Matrix) -> Matrix:
    """Represent a sum-preserving full operator in the fixed zero-sum basis."""

    basis = zero_sum_basis()
    image = _matrix_multiply(full_operator, basis)
    # A vector B*y has its first eleven coordinates equal to y.  Every seam
    # generator preserves V_0, so these rows are the exact restricted matrix.
    return tuple(image[row] for row in range(ZERO_SUM_DIMENSION))


def seam_disagreement_generators() -> tuple[Matrix, ...]:
    """Return the thirty integral matrices ``G_e=b_e b_e^T`` on ``V_0``."""

    rows: list[Matrix] = []
    for left, right in exact_reference_edges():
        difference = [0] * PORT_COUNT
        difference[left] = 1
        difference[right] = -1
        full = tuple(
            tuple(difference[row] * difference[column] for column in range(PORT_COUNT))
            for row in range(PORT_COUNT)
        )
        rows.append(_restrict_zero_sum(full))
    return tuple(rows)


def first_nonzero_commutators(
    generators: Sequence[Matrix] | None = None,
) -> tuple[Matrix, ...]:
    """Return all nonzero unordered first commutators in canonical order."""

    source = tuple(generators or seam_disagreement_generators())
    rows: list[Matrix] = []
    for left_index in range(len(source)):
        for right_index in range(left_index):
            candidate = _commutator(
                source[left_index],
                source[right_index],
            )
            if not _is_zero(candidate):
                rows.append(candidate)
    return tuple(rows)


def exact_rational_rank(matrices: Sequence[Matrix]) -> int:
    """Compute the exact row rank of flattened integer matrices over Q."""

    if not matrices:
        return 0
    rows = [
        [Fraction(value) for value in _flatten(matrix)]
        for matrix in matrices
    ]
    row_count = len(rows)
    column_count = len(rows[0])
    rank = 0
    column = 0
    while rank < row_count and column < column_count:
        pivot = next(
            (
                candidate
                for candidate in range(rank, row_count)
                if rows[candidate][column]
            ),
            None,
        )
        if pivot is None:
            column += 1
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        pivot_value = rows[rank][column]
        for position in range(column, column_count):
            rows[rank][position] /= pivot_value
        for candidate in range(rank + 1, row_count):
            factor = rows[candidate][column]
            if not factor:
                continue
            for position in range(column, column_count):
                rows[candidate][position] -= factor * rows[rank][position]
        rank += 1
        column += 1
    return rank


class _ModularBasis:
    """Deterministic incremental row basis over one prime field."""

    def __init__(self, prime: int) -> None:
        self.prime = int(prime)
        self._rows: dict[int, tuple[int, ...]] = {}

    @property
    def rank(self) -> int:
        return len(self._rows)

    def add(self, values: Iterable[int]) -> bool:
        row = [int(value) % self.prime for value in values]
        for pivot, basis_row in self._rows.items():
            factor = row[pivot]
            if factor:
                row = [
                    (value - factor * base) % self.prime
                    for value, base in zip(row, basis_row, strict=True)
                ]
        pivot = next(
            (position for position, value in enumerate(row) if value),
            None,
        )
        if pivot is None:
            return False
        inverse = pow(row[pivot], self.prime - 2, self.prime)
        normalized = tuple((value * inverse) % self.prime for value in row)
        self._rows[pivot] = normalized
        self._rows = dict(sorted(self._rows.items()))
        return True


def modular_rank(matrices: Sequence[Matrix], prime: int) -> int:
    basis = _ModularBasis(prime)
    for matrix in matrices:
        basis.add(_flatten(matrix))
    return basis.rank


def _independent_modular_basis(
    matrices: Sequence[Matrix],
    prime: int,
) -> tuple[list[Matrix], _ModularBasis]:
    reducer = _ModularBasis(prime)
    selected: list[Matrix] = []
    for matrix in matrices:
        if reducer.add(_flatten(matrix)):
            selected.append(matrix)
    return selected, reducer


def metric_self_adjoint(matrix: Matrix, gram: Matrix | None = None) -> bool:
    metric = gram or zero_sum_gram_matrix()
    return _matrix_multiply(metric, matrix) == _matrix_multiply(
        _transpose(matrix),
        metric,
    )


def metric_skew(matrix: Matrix, gram: Matrix | None = None) -> bool:
    metric = gram or zero_sum_gram_matrix()
    return _is_zero(
        _matrix_add(
            _matrix_multiply(metric, matrix),
            _matrix_multiply(_transpose(matrix), metric),
        )
    )


def compact_commutator_closure(
    seed: Sequence[Matrix],
    *,
    prime: int = RANK_PRIMES[0],
) -> tuple[tuple[Matrix, ...], tuple[int, ...]]:
    """Close an H-skew seed under brackets using exact integer matrices."""

    selected, reducer = _independent_modular_basis(seed, prime)
    round_ranks = [len(selected)]
    while True:
        previous_rank = len(selected)
        snapshot = tuple(selected)
        for left_index in range(len(snapshot)):
            for right_index in range(left_index):
                candidate = _commutator(
                    snapshot[left_index],
                    snapshot[right_index],
                )
                if reducer.add(_flatten(candidate)):
                    selected.append(candidate)
        round_ranks.append(len(selected))
        if len(selected) == previous_rank:
            break
        if len(selected) > ZERO_SUM_DIMENSION * (ZERO_SUM_DIMENSION - 1) // 2:
            raise ValueError("metric-skew closure exceeded its structural upper bound")
    return tuple(selected), tuple(round_ranks)


def generated_operator_algebra(
    generators: Sequence[Matrix],
    *,
    prime: int = RANK_PRIMES[0],
) -> tuple[tuple[Matrix, ...], tuple[int, ...]]:
    """Return a modularly independent basis of the generated unital algebra."""

    identity = _identity(ZERO_SUM_DIMENSION)
    selected, reducer = _independent_modular_basis(
        (identity, *tuple(generators)),
        prime,
    )
    round_ranks = [len(selected)]
    upper_bound = ZERO_SUM_DIMENSION * ZERO_SUM_DIMENSION
    while True:
        previous_rank = len(selected)
        snapshot = tuple(selected)
        for current in snapshot:
            for generator in generators:
                for candidate in (
                    _matrix_multiply(current, generator),
                    _matrix_multiply(generator, current),
                ):
                    if reducer.add(_flatten(candidate)):
                        selected.append(candidate)
                    if len(selected) == upper_bound:
                        break
                if len(selected) == upper_bound:
                    break
            if len(selected) == upper_bound:
                break
        round_ranks.append(len(selected))
        if len(selected) in (previous_rank, upper_bound):
            break
    return tuple(selected), tuple(round_ranks)


def build_report() -> dict[str, Any]:
    """Recompute the exact seam-current exclusion control."""

    edges = exact_reference_edges()
    generators = seam_disagreement_generators()
    gram = zero_sum_gram_matrix()
    first = first_nonzero_commutators(generators)
    first_exact_rank = exact_rational_rank(first)
    first_modular_ranks = {
        str(prime): modular_rank(first, prime)
        for prime in RANK_PRIMES
    }

    compact_basis, compact_round_ranks = compact_commutator_closure(first)
    compact_exact_rank = exact_rational_rank(compact_basis)
    compact_modular_ranks = {
        str(prime): modular_rank(compact_basis, prime)
        for prime in RANK_PRIMES
    }
    compact_upper_bound = (
        ZERO_SUM_DIMENSION * (ZERO_SUM_DIMENSION - 1) // 2
    )
    compact_metric_skew = all(
        metric_skew(matrix, gram)
        for matrix in compact_basis
    )

    operator_basis, operator_round_ranks = generated_operator_algebra(
        generators
    )
    operator_exact_rank = exact_rational_rank(operator_basis)
    operator_modular_ranks = {
        str(prime): modular_rank(operator_basis, prime)
        for prime in RANK_PRIMES
    }
    operator_upper_bound = ZERO_SUM_DIMENSION * ZERO_SUM_DIMENSION

    generator_self_adjoint = all(
        metric_self_adjoint(matrix, gram)
        for matrix in generators
    )
    result: dict[str, Any] = {
        "schema": SCHEMA,
        "status": STATUS,
        "source": {
            "oriented_face_sha256": _sha256(
                [list(face) for face in ORIENTED_BASE_FACES]
            ),
            "undirected_seams": [list(edge) for edge in edges],
            "undirected_seam_count": len(edges),
            "source_module": (
                "oph_fpe.dynamics.self_readback_repair_closure."
                "exact_reference_edges"
            ),
            "target_fields_read_by_rank_engine": [],
            "laboratory_measurements_read": False,
        },
        "zero_sum_representation": {
            "ambient_port_dimension": PORT_COUNT,
            "protected_constant_dimension": 1,
            "zero_sum_dimension": ZERO_SUM_DIMENSION,
            "basis": "e_i-e_11 for i=0,...,10",
            "basis_matrix_sha256": _sha256(
                [list(row) for row in zero_sum_basis()]
            ),
            "gram_matrix": [list(row) for row in gram],
            "gram_positive_definite": True,
        },
        "seam_equalizers": {
            "equalizer": "E_e = I - (1/2) b_e b_e^T",
            "integral_generator": "G_e = 2(I-E_e) = b_e b_e^T",
            "generator_count": len(generators),
            "generator_exact_rational_rank": exact_rational_rank(generators),
            "all_generators_metric_self_adjoint": generator_self_adjoint,
            "generator_packet_sha256": _sha256(
                [
                    [list(row) for row in matrix]
                    for matrix in generators
                ]
            ),
        },
        "first_commutators": {
            "unordered_generator_pair_count": len(generators)
            * (len(generators) - 1)
            // 2,
            "nonzero_commutator_count": len(first),
            "exact_rational_rank": first_exact_rank,
            "modular_ranks": first_modular_ranks,
            "packet_sha256": _sha256(
                [
                    [list(row) for row in matrix]
                    for matrix in first
                ]
            ),
        },
        "compact_lie_closure": {
            "closure_operation": "matrix_commutator",
            "modular_basis_round_ranks": list(compact_round_ranks),
            "exact_rational_rank_of_witness_basis": compact_exact_rank,
            "modular_ranks_of_witness_basis": compact_modular_ranks,
            "metric_skew_witness": compact_metric_skew,
            "metric_skew_structural_upper_bound": compact_upper_bound,
            "identified_algebra": (
                "so(V_0,H), hence the compact real algebra so(11)"
                if compact_exact_rank == compact_upper_bound
                and compact_metric_skew
                else None
            ),
            "witness_basis_sha256": _sha256(
                [
                    [list(row) for row in matrix]
                    for matrix in compact_basis
                ]
            ),
        },
        "generated_operator_algebra": {
            "closure_operation": (
                "unital left-and-right multiplication by seam generators"
            ),
            "equalizer_and_generator_unital_algebras_agree": True,
            "modular_basis_round_ranks": list(operator_round_ranks),
            "exact_rational_rank_of_witness_basis": operator_exact_rank,
            "modular_ranks_of_witness_basis": operator_modular_ranks,
            "endomorphism_structural_upper_bound": operator_upper_bound,
            "identified_algebra": (
                "End_Q(V_0), extending over R to all 11x11 operators"
                if operator_exact_rank == operator_upper_bound
                else None
            ),
            "witness_basis_sha256": _sha256(
                [
                    [list(row) for row in matrix]
                    for matrix in operator_basis
                ]
            ),
        },
        "current_identification_control": {
            "comparison_target_dimension": 12,
            "comparison_used_to_construct_generators_or_ranks": False,
            "repair_equalizer_compact_closure_dimension": compact_exact_rank,
            "repair_equalizer_operator_algebra_dimension": operator_exact_rank,
            "repair_equalizers_are_the_desired_12d_compact_current": False,
            "conclusion": (
                "The scalar seam equalizers cannot be identified with the "
                "desired twelve-dimensional compact port current. A separate "
                "reversible-response and same-current internal-holonomy "
                "producer is required."
            ),
        },
        "receipts": {
            "SEAM_EQUALIZER_FIRST_COMMUTATOR_RANK_49_RECEIPT": (
                first_exact_rank == 49
                and set(first_modular_ranks.values()) == {49}
            ),
            "SEAM_EQUALIZER_SO11_CLOSURE_RECEIPT": (
                compact_exact_rank == 55
                and set(compact_modular_ranks.values()) == {55}
                and compact_metric_skew
                and compact_upper_bound == 55
            ),
            "SEAM_EQUALIZER_FULL_OPERATOR_ALGEBRA_RECEIPT": (
                operator_exact_rank == 121
                and set(operator_modular_ranks.values()) == {121}
                and operator_upper_bound == 121
            ),
            "SEAM_EQUALIZER_IS_12D_COMPACT_CURRENT_RECEIPT": False,
        },
        "claim_boundary": (
            "Exact finite control on the scalar twelve-port seam equalizers. "
            "It excludes one proposed identification with a twelve-dimensional "
            "compact current algebra. It does not exclude a separately derived "
            "reversible OPH response algebra and is not a falsification of OPH."
        ),
    }
    if not all(
        (
            result["receipts"][
                "SEAM_EQUALIZER_FIRST_COMMUTATOR_RANK_49_RECEIPT"
            ],
            result["receipts"]["SEAM_EQUALIZER_SO11_CLOSURE_RECEIPT"],
            result["receipts"][
                "SEAM_EQUALIZER_FULL_OPERATOR_ALGEBRA_RECEIPT"
            ],
            result["current_identification_control"][
                "repair_equalizers_are_the_desired_12d_compact_current"
            ]
            is False,
        )
    ):
        raise ValueError("the exact seam-current control did not reach its frozen exit")
    result["report_sha256"] = _sha256(result)
    return result


def verify_report(report: Mapping[str, Any]) -> dict[str, Any]:
    """Recompute the report and reject any semantic or byte-level mutation."""

    expected = build_report()
    supplied = copy.deepcopy(dict(report))
    passed = supplied == expected
    return {
        "schema": "oph.seam-equalizer-current-control-verification/1.0.0",
        "passed": passed,
        "expected_report_sha256": expected["report_sha256"],
        "supplied_report_sha256": supplied.get("report_sha256"),
        "reason": (
            "byte-exact semantic replay matched"
            if passed
            else "supplied report differs from exact recomputation"
        ),
    }


def render_report(report: Mapping[str, Any]) -> str:
    return json.dumps(report, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--verify", type=Path)
    args = parser.parse_args()
    if args.verify is not None:
        supplied = json.loads(args.verify.read_text(encoding="utf-8"))
        verification = verify_report(supplied)
        print(render_report(verification), end="")
        return 0 if verification["passed"] else 1
    report = build_report()
    rendered = render_report(report)
    if args.out is None:
        print(rendered, end="")
    else:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "RANK_PRIMES",
    "SCHEMA",
    "STATUS",
    "ZERO_SUM_DIMENSION",
    "build_report",
    "compact_commutator_closure",
    "exact_rational_rank",
    "first_nonzero_commutators",
    "generated_operator_algebra",
    "metric_self_adjoint",
    "metric_skew",
    "modular_rank",
    "render_report",
    "seam_disagreement_generators",
    "verify_report",
    "zero_sum_basis",
    "zero_sum_gram_matrix",
]
