from __future__ import annotations

from typing import Any


RECEIPT_SCHEMA_VERSION = "2026-06-06b"


RECOVERED_CORE = "recovered_core"
QUANTITATIVE_BRANCH = "quantitative_branch"
CONTINUATION = "continuation"
PROXY = "proxy"
DEMO = "demo"
DEBUG = "debug"
BRANCH_INSTANTIATION_SANITY = "branch_instantiation_sanity"
DECLARED_SHAPE_SUBSTRATE_WITNESS = "declared_shape_substrate_witness"

CLAIM_LEVELS = {
    RECOVERED_CORE,
    QUANTITATIVE_BRANCH,
    CONTINUATION,
    PROXY,
    DEMO,
    DEBUG,
    BRANCH_INSTANTIATION_SANITY,
    DECLARED_SHAPE_SUBSTRATE_WITNESS,
}

REPAIR_CORE_RECEIPT = "REPAIR_CORE_RECEIPT"
FINITE_SETTLE_DIAGNOSTIC_RECEIPT = "FINITE_SETTLE_DIAGNOSTIC_RECEIPT"
FINITE_CONSENSUS_THEOREM_RECEIPT = "FINITE_CONSENSUS_THEOREM_RECEIPT"
RECORD_COMMIT_RECEIPT = "RECORD_COMMIT_RECEIPT"
BW_KMS_BRANCH_REPLAY_RECEIPT = "BW_KMS_BRANCH_REPLAY_RECEIPT"
BW_KMS_BRANCH_INSTANTIATION_RECEIPT = "BW_KMS_BRANCH_INSTANTIATION_RECEIPT"
ISSUE_307_COLLAR_CMI_DECAY_RECEIPT = "ISSUE_307_COLLAR_CMI_DECAY_FINITE_RECEIPT"
ISSUE_308_BW_CERTIFICATE_RECEIPT = "ISSUE_308_FINITE_CAP_BW_CERTIFICATE_RECEIPT"
CAP_NORMAL_H3_CHART_RECEIPT = "CAP_NORMAL_H3_CHART_RECEIPT"
MODULAR_RESPONSE_H3_LOCALIZATION_RECEIPT = "MODULAR_RESPONSE_H3_LOCALIZATION_RECEIPT"
MATSCHEKO_PROOF_CHAIN_IMPORT_RECEIPT = "MATSCHEKO_PROOF_CHAIN_IMPORT_RECEIPT"
P_BRANCH_PROVENANCE_RECEIPT = "P_BRANCH_PROVENANCE_RECEIPT"
CHI_NU_G9_RECORD_GRAVITY_BRIDGE_RECEIPT = "CHI_NU_G9_RECORD_GRAVITY_BRIDGE_RECEIPT"
CHI_NU_G10_ENERGY_LEDGER_THEOREM_RECEIPT = "CHI_NU_G10_ENERGY_LEDGER_THEOREM_RECEIPT"
FINITE_MODULAR_FLOW_IMPORT_RECEIPT = "FINITE_MODULAR_FLOW_IMPORT_RECEIPT"
SCALAR_CHANNEL_BRIDGE_IMPORT_RECEIPT = "SCALAR_CHANNEL_BRIDGE_IMPORT_RECEIPT"
TWELVE_PORT_SURFACE_IMPORT_RECEIPT = "TWELVE_PORT_SURFACE_IMPORT_RECEIPT"
QBFT_BOUNDARY_CAVEAT_RECEIPT = "QBFT_BOUNDARY_CAVEAT_RECEIPT"
RULE90_PARITY_SPLITTING_IMPORT_RECEIPT = "RULE90_PARITY_SPLITTING_IMPORT_RECEIPT"
RULE90_TWO_POWER_UNIVERSALITY_IMPORT_RECEIPT = "RULE90_TWO_POWER_UNIVERSALITY_IMPORT_RECEIPT"
RULE90_DIAGONAL_SCREEN_IMPORT_RECEIPT = "RULE90_DIAGONAL_SCREEN_IMPORT_RECEIPT"
CONFORMAL_H3_CHART_RECEIPT = "CONFORMAL_H3_CHART_RECEIPT"
CHART_LORENTZ_H3_RECEIPT = "CHART_LORENTZ_H3_RECEIPT"
PAPER_THEOREM_3D_BULK_CHART_RECEIPT = "PAPER_THEOREM_3D_BULK_CHART_RECEIPT"
BW_KMS_DIRECT_2PI_RECEIPT = "BW_KMS_DIRECT_2PI_RECEIPT"
ENDOGENOUS_MODULAR_GENERATOR_RECEIPT = "ENDOGENOUS_MODULAR_GENERATOR_RECEIPT"
OPH_LORENTZ_THEOREM_FINITE_CONTRACT_RECEIPT = "OPH_LORENTZ_THEOREM_FINITE_CONTRACT_V1"
OPH_EINSTEIN_BRANCH_ENTRY_CONTRACT_RECEIPT = "OPH_EINSTEIN_BRANCH_ENTRY_CONTRACT_V1"
EINSTEIN_BRANCH_ENTRY_RECEIPT = "EINSTEIN_BRANCH_ENTRY_RECEIPT"
EINSTEIN_BRANCH_ISSUE_503_RECEIPT = "EINSTEIN_BRANCH_ISSUE_503_RECEIPT"
OPH_EINSTEIN_BRIDGE_MANIFEST_RECEIPT = "OPH_EINSTEIN_BRIDGE_MANIFEST_V1"
EINSTEIN_BRIDGE_DEPENDENCY_DISCHARGE_RECEIPT = "EINSTEIN_BRIDGE_DEPENDENCY_DISCHARGE_RECEIPT"
EINSTEIN_BRIDGE_RUN_RECEIPTS_RECEIPT = "EINSTEIN_BRIDGE_RUN_RECEIPTS_RECEIPT"
EINSTEIN_NULL_STRESS_CHARGE_RECEIPT = "EINSTEIN_NULL_STRESS_CHARGE_RECEIPT"
EINSTEIN_FIXED_CAP_ENTROPY_STATIONARITY_RECEIPT = (
    "EINSTEIN_FIXED_CAP_ENTROPY_STATIONARITY_RECEIPT"
)
EINSTEIN_SMALL_BALL_AREA_BRIDGE_RECEIPT = "EINSTEIN_SMALL_BALL_AREA_BRIDGE_RECEIPT"
EINSTEIN_ALL_TIMELIKE_TENSOR_UPGRADE_RECEIPT = "EINSTEIN_ALL_TIMELIKE_TENSOR_UPGRADE_RECEIPT"
EINSTEIN_BOUNDED_INTERVAL_KERNEL_RECEIPT = "EINSTEIN_BOUNDED_INTERVAL_KERNEL_RECEIPT"
EINSTEIN_DIAGONAL_REMAINDER_RECEIPT = "EINSTEIN_DIAGONAL_REMAINDER_RECEIPT"
EINSTEIN_TIMELIKE_COVERAGE_RECEIPT = "EINSTEIN_TIMELIKE_COVERAGE_RECEIPT"
EINSTEIN_STRESS_CLOSURE_RECEIPT = "EINSTEIN_STRESS_CLOSURE_RECEIPT"
EINSTEIN_RESIDUAL_RECEIPT = "EINSTEIN_RESIDUAL_RECEIPT"
EINSTEIN_LAMBDA_CONSTANCY_CONSERVATION_RECEIPT = (
    "EINSTEIN_LAMBDA_CONSTANCY_CONSERVATION_RECEIPT"
)
EINSTEIN_NEWTON_COUPLING_FORBIDDEN_INPUT_AUDIT_RECEIPT = (
    "EINSTEIN_NEWTON_COUPLING_FORBIDDEN_INPUT_AUDIT_RECEIPT"
)
PRODUCTION_GRAVITY_RECEIPT = "PRODUCTION_GRAVITY_RECEIPT"
PHYSICAL_GRAVITY_PREDICTION_RECEIPT = "PHYSICAL_GRAVITY_PREDICTION_RECEIPT"
H3_RESPONSE_CONTROL_SEPARATION_RECEIPT = "H3_RESPONSE_CONTROL_SEPARATION_RECEIPT"
H3_RESPONSE_CANDIDATE_RECEIPT = "H3_RESPONSE_CANDIDATE_RECEIPT"
OBJECT_CHART_RECEIPT = "OBJECT_CHART_RECEIPT"
OBJECT_BULK_POPULATION_RECEIPT = "OBJECT_BULK_POPULATION_RECEIPT"
SUPPORT_VISIBLE_H3_POPULATED_BULK_RECEIPT = "SUPPORT_VISIBLE_H3_POPULATED_BULK_RECEIPT"
PRIME_GEOMETRIC_QUOTIENT_3D_DIAGNOSTIC_RECEIPT = "PRIME_GEOMETRIC_QUOTIENT_3D_DIAGNOSTIC_RECEIPT"
OBSERVER_FACING_3P1D_H3_EXPERIENCE_RECEIPT = "OBSERVER_FACING_3P1D_H3_EXPERIENCE_RECEIPT"
THEOREM_ASSISTED_H3_OBJECT_POPULATION_RECEIPT = "THEOREM_ASSISTED_H3_OBJECT_POPULATION_RECEIPT"
CONTROL_RESIDUALIZED_RANK3_CANDIDATE_RECEIPT = "CONTROL_RESIDUALIZED_RANK3_CANDIDATE_RECEIPT"
STRICT_NEUTRAL_LATENT_H3_SELECTION_RECEIPT = "STRICT_NEUTRAL_LATENT_H3_SELECTION_RECEIPT"
STRICT_NEUTRAL_OBJECT_BULK_RECEIPT = "STRICT_NEUTRAL_OBJECT_BULK_RECEIPT"
STRICT_NEUTRAL_BULK_RECEIPT = "STRICT_NEUTRAL_BULK_RECEIPT"
SCREEN_DEFECT_DYNAMICS_RECEIPT = "SCREEN_DEFECT_DYNAMICS_RECEIPT"
H3_DEFECT_WORLDLINE_RECEIPT = "H3_DEFECT_WORLDLINE_RECEIPT"
PROTO_PARTICLE_RECEIPT = "PROTO_PARTICLE_RECEIPT"
BULK_WORLDLINE_PRECURSOR_RECEIPT = "BULK_WORLDLINE_PRECURSOR_RECEIPT"
CLASSICAL_CARRIER_MODE_RECEIPT = "CLASSICAL_CARRIER_MODE_RECEIPT"
QUANTUM_PARTICLE_RECEIPT = "QUANTUM_PARTICLE_RECEIPT"
COLORED_DECONFINEMENT_RECEIPT = "COLORED_DECONFINEMENT_RECEIPT"
PRODUCTION_PARTICLE_MATTER_RECEIPT = "PRODUCTION_PARTICLE_MATTER_RECEIPT"
SCREEN_PROXY_CMB_RECEIPT = "SCREEN_PROXY_CMB_RECEIPT"
STATIC_GALAXY_LAW_RECEIPT = "STATIC_GALAXY_LAW_RECEIPT"
STATIC_GALAXY_RAR_BTFR_RECEIPT = "STATIC_GALAXY_RAR_BTFR_RECEIPT"
OPH_STATIC_GALAXY_BRIDGE_RECEIPT = "OPH_STATIC_GALAXY_BRIDGE_RECEIPT"
DYNAMIC_DARK_TRANSPORT_RECEIPT = "DYNAMIC_DARK_TRANSPORT_RECEIPT"
OPH_BOLTZMANN_KERNEL_RECEIPT = "OPH_BOLTZMANN_KERNEL_RECEIPT"
PHYSICAL_CMB_RECEIPT = "PHYSICAL_CMB_RECEIPT"
COSMOLOGY_PERTURBATION_RECEIPT = "COSMOLOGY_PERTURBATION_RECEIPT"
SHAPE_VERTEX_SCATTERING_RECEIPT = "SHAPE_VERTEX_SCATTERING_RECEIPT"
SHAPE_DODECA_CELL_RECEIPT = "SHAPE_DODECA_CELL_RECEIPT"
SHAPE_LOOP_MODE_RECEIPT = "SHAPE_LOOP_MODE_RECEIPT"
SHAPE_SETTLING_RECEIPT = "SHAPE_SETTLING_RECEIPT"
SHAPE_LOOP_PARTICLE_RECEIPT = "SHAPE_LOOP_PARTICLE_RECEIPT"
SHAPE_SCREEN_PROJECTION_RECEIPT = "SHAPE_SCREEN_PROJECTION_RECEIPT"
SHAPE_CMB_CERTIFICATE_INPUT_RECEIPT = "SHAPE_CMB_CERTIFICATE_INPUT_RECEIPT"
SHAPE_VISIBLE_IR_TARGET_RECEIPT = "SHAPE_VISIBLE_IR_TARGET_RECEIPT"
SHAPE_FOUR_SECTOR_IR_RECEIPT = "SHAPE_FOUR_SECTOR_IR_RECEIPT"
DECLARED_SHAPE_SUBSTRATE_WITNESS_RECEIPT = "DECLARED_SHAPE_SUBSTRATE_WITNESS_RECEIPT"

CANONICAL_RECEIPTS = {
    "R0": REPAIR_CORE_RECEIPT,
    "R1": RECORD_COMMIT_RECEIPT,
    "R2": BW_KMS_BRANCH_REPLAY_RECEIPT,
    "R3": CHART_LORENTZ_H3_RECEIPT,
    "R4": H3_RESPONSE_CANDIDATE_RECEIPT,
    "R5": OBJECT_CHART_RECEIPT,
    "R6": OBJECT_BULK_POPULATION_RECEIPT,
    "R7": SCREEN_PROXY_CMB_RECEIPT,
    "R8": STATIC_GALAXY_RAR_BTFR_RECEIPT,
    "R9": DYNAMIC_DARK_TRANSPORT_RECEIPT,
    "R10": COSMOLOGY_PERTURBATION_RECEIPT,
    "P0": BULK_WORLDLINE_PRECURSOR_RECEIPT,
    "P1": PRODUCTION_PARTICLE_MATTER_RECEIPT,
}


def receipt_meta(
    *,
    receipt: str,
    claim_level: str,
    physical_claim: bool,
    observable_id: str,
    fit_objective: str,
) -> dict[str, Any]:
    return {
        "receipt_schema_version": RECEIPT_SCHEMA_VERSION,
        "receipt_name": str(receipt),
        "claim_level": checked_claim_level(claim_level),
        "physical_claim": bool(physical_claim),
        "observable_id": str(observable_id),
        "fit_objective": str(fit_objective),
    }


def checked_claim_level(value: str) -> str:
    level = str(value)
    if level not in CLAIM_LEVELS:
        raise ValueError(f"unknown OPH claim level: {value}")
    return level


def with_claim_metadata(
    report: dict[str, Any],
    *,
    claim_level: str,
    receipt: str | None = None,
    physical_claim: bool | None = None,
    observable_id: str | None = None,
    fit_objective: str | None = None,
) -> dict[str, Any]:
    result = dict(report)
    result["receipt_schema_version"] = RECEIPT_SCHEMA_VERSION
    result["claim_level"] = checked_claim_level(claim_level)
    if receipt is not None:
        result["receipt_name"] = str(receipt)
    result["observable_id"] = str(
        observable_id
        or result.get("observable_id")
        or receipt
        or result.get("mode")
        or "unspecified"
    )
    result["fit_objective"] = str(fit_objective or result.get("fit_objective") or "not_applicable")
    if physical_claim is None:
        result.setdefault("physical_claim", False)
    else:
        result["physical_claim"] = bool(physical_claim)
    return result
