from __future__ import annotations

from dataclasses import dataclass
import math

from oph_fpe.constants.oph_pixel import P_STAR
from oph_fpe.cosmology.neutrino_status import (
    CONVENTIONAL_CAMB_NEUTRINO_ASSUMPTION,
    CONVENTIONAL_CAMB_SUM_MNU_EV,
)

DEFAULT_R_DS_M = 1.66e26
DEFAULT_L_PLANCK_M = 1.616e-35
DEFAULT_OBSERVED_HORIZON_N_COMPARISON = math.pi * (
    DEFAULT_R_DS_M / DEFAULT_L_PLANCK_M
) ** 2
# Compatibility alias used by historical diagnostics.  It is not an OPH
# public-record-capacity producer; physical N must come from the exact
# PUBLIC_CHECKPOINT_PACKET evaluator and its closure receipts.
DEFAULT_N_CRC = DEFAULT_OBSERVED_HORIZON_N_COMPARISON
LAMBDA_COLLAR_EXACT_GATE = "UNIFORM_PRODUCT_THICKENING_EXACT"

# ---------------------------------------------------------------------------
# Source-derived electroweak-branch capacity N_CRC_EW (non-circular).
#
# Unlike DEFAULT_OBSERVED_HORIZON_N_COMPARISON above (derived from the measured
# R_dS, hence circular for any Lambda readout), these values are generated on
# the source side by the declared electroweak bridge
#     N_EW(P) = pi * exp(6*pi / (P * alpha_U(P)))
# on the two branch-tagged (P, alpha_U) pairs pinned in the imported cross-repo
# artifact.  Both values below replay from fields of that single artifact.
SOURCE_DERIVED_N_CRC_EW_ARTIFACT = (
    "data/oph_cross_repo_current/imported_oph_artifacts/particle_derivation_gap_ledger.json"
)
SOURCE_DERIVED_N_CRC_EW_SOURCE = "source_derived_electroweak_bridge"
SOURCE_DERIVED_N_CRC_EW_BRIDGE_FORMULA = "N_EW(P) = pi * exp(6*pi / (P * alpha_U(P)))"

# Branch 1: comparison pixel (public endpoint branch, P_C).  The artifact
# stores this decimal directly; it replays (relative deviation ~6e-35) as the
# bridge formula on electroweak_hierarchy.public_endpoint_branch.{P, alpha_U}.
N_CRC_EW_COMPARISON_PIXEL_DECIMAL = (
    "3.5323546226929906511187512962330547600462096590942035604238177731136802717"
    "148740820434110040644403858228611984E+122"
)
N_CRC_EW_COMPARISON_PIXEL = float(N_CRC_EW_COMPARISON_PIXEL_DECIMAL)
N_CRC_EW_COMPARISON_PIXEL_PROVENANCE = (
    f"{SOURCE_DERIVED_N_CRC_EW_ARTIFACT}"
    ":electroweak_hierarchy.N_CRC_EW (stored decimal; replays as "
    "pi*exp(6*pi/(P*alpha_U)) on electroweak_hierarchy.public_endpoint_branch"
    ".{P, alpha_U})"
)

# Branch 2: forward closure point (source audit branch, P_fwd).  Generated by
# the same bridge formula from the certified source-audit pair pinned in the
# same artifact (mpmath dps=60 evaluation, outward digits truncated at 40).
N_CRC_EW_FORWARD_CLOSURE_POINT_DECIMAL = "3.532131543418935831227120443019323145702E+122"
N_CRC_EW_FORWARD_CLOSURE_POINT = float(N_CRC_EW_FORWARD_CLOSURE_POINT_DECIMAL)
N_CRC_EW_FORWARD_CLOSURE_POINT_PROVENANCE = (
    f"{SOURCE_DERIVED_N_CRC_EW_ARTIFACT}"
    ":electroweak_hierarchy.source_audit_branch.{P, alpha_U} via "
    "pi*exp(6*pi/(P*alpha_U))"
)

SOURCE_DERIVED_N_CRC_EW_DEFAULT_BRANCH = "comparison_pixel"
# Default source-derived value: the comparison-pixel branch, matching the
# public cross-repo surfaces that cite 3.5323546e122.
SOURCE_DERIVED_N_CRC_EW = N_CRC_EW_COMPARISON_PIXEL


def source_derived_n_crc_ew_jsonable(
    observed_horizon_comparison: float = DEFAULT_OBSERVED_HORIZON_N_COMPARISON,
) -> dict[str, object]:
    """Branch-tagged source-derived N_CRC_EW block for report emitters."""

    return {
        "source": SOURCE_DERIVED_N_CRC_EW_SOURCE,
        "producer_eligible": True,
        "distinct_from_observed_horizon_comparison": True,
        "bridge_formula": SOURCE_DERIVED_N_CRC_EW_BRIDGE_FORMULA,
        "default_branch": SOURCE_DERIVED_N_CRC_EW_DEFAULT_BRANCH,
        "branches": {
            "comparison_pixel": {
                "value": N_CRC_EW_COMPARISON_PIXEL,
                "decimal": N_CRC_EW_COMPARISON_PIXEL_DECIMAL,
                "provenance": N_CRC_EW_COMPARISON_PIXEL_PROVENANCE,
            },
            "forward_closure_point": {
                "value": N_CRC_EW_FORWARD_CLOSURE_POINT,
                "decimal": N_CRC_EW_FORWARD_CLOSURE_POINT_DECIMAL,
                "provenance": N_CRC_EW_FORWARD_CLOSURE_POINT_PROVENANCE,
            },
        },
        "ratio_source_derived_over_observed_horizon": {
            "comparison_pixel": N_CRC_EW_COMPARISON_PIXEL / float(observed_horizon_comparison),
            "forward_closure_point": (
                N_CRC_EW_FORWARD_CLOSURE_POINT / float(observed_horizon_comparison)
            ),
        },
        "claim_boundary": (
            "Source-derived electroweak-branch capacity imported from the cross-repo "
            "gap ledger; exact-conditional on the ledger's declared screen premises. "
            "It is not the quarantined observed-horizon comparison and does not by "
            "itself close the finite-simulator capacity fixed point."
        ),
    }


@dataclass(frozen=True)
class OPHConstants:
    """Constants shared by OPH cosmology diagnostic lanes.

    These are comparison/readout constants.  In particular, ``N_CRC`` defaults
    to an observed-horizon comparison and cannot define public-record capacity.
    They do not by themselves close the finite-lattice derivation gate for
    B_A(k,a), neutrino masses, physical N, or a physical Boltzmann likelihood.
    """

    P: float = P_STAR
    N_CRC: float = DEFAULT_N_CRC
    N_CRC_source: str = "observed_horizon_comparison"
    N_CRC_producer_eligible: bool = False
    pi_wl: float = 5.0 / 7.0
    conventional_camb_sum_mnu_eV: float = CONVENTIONAL_CAMB_SUM_MNU_EV
    N_eff: float = 3.044
    S8_oph_compressed: float = 0.828924043
    S8_wl_target_reference: float = 0.790
    S8_wl_sigma_reference: float = 0.016

    @property
    def z6_normalized_trace_mean(self) -> float:
        return float(self.P) / 24.0

    @property
    def z6_reciprocal_trace(self) -> float:
        return 24.0 / float(self.P)

    @property
    def lambda_collar_exact_uniform_product_thickening(self) -> float:
        """Exact-uniform/product-thickening diagnostic target.

        Finite-thickness runs must promote this through the
        UNIFORM_PRODUCT_THICKENING_EXACT gate before using it as a physical
        local coefficient.
        """

        return math.exp(-float(self.P) / 24.0)

    @property
    def lambda_collar(self) -> float:
        return self.lambda_collar_exact_uniform_product_thickening

    @property
    def lambda_collar_exact_gate(self) -> str:
        return LAMBDA_COLLAR_EXACT_GATE

    @property
    def lambda_collar_claim_status(self) -> str:
        return "diagnostic_exact_uniform_product_thickening_target_not_unconditional"

    @property
    def lambda_collar_profile_default(self) -> str:
        return "lambda_collar = integral dy w(y) exp[-epsilon_Z6(y)]"

    @property
    def finite_thickness_jensen_band(self) -> list[float]:
        return [self.lambda_collar_exact_uniform_product_thickening, 1.0]

    @property
    def reserve(self) -> float:
        return 1.0 - self.lambda_collar

    @property
    def epsilon_A_wl(self) -> float:
        return self.pi_wl * self.reserve

    @property
    def R_wl(self) -> float:
        return 1.0 - self.epsilon_A_wl

    @property
    def S8_projected_wl(self) -> float:
        return self.S8_oph_compressed * self.R_wl

    @property
    def N_patch_bare_ratio(self) -> float:
        return float(self.N_CRC) / math.pi

    @property
    def Lambda_lP2(self) -> float:
        return 3.0 * math.pi / float(self.N_CRC)

    @property
    def P_cell_count_for_N_CRC(self) -> float:
        return 4.0 * float(self.N_CRC) / float(self.P)

    def as_jsonable(self) -> dict[str, object]:
        return {
            "P": float(self.P),
            "N_CRC": float(self.N_CRC),
            "N_CRC_source": self.N_CRC_source,
            "N_CRC_producer_eligible": bool(self.N_CRC_producer_eligible),
            "N_CRC_contract": (
                "comparison only; physical N requires exact target-free public-record "
                "capacity, complete-fiber scalarization, robust closure, unique "
                "regulator-stable slack zero, and horizon-record saturation"
            ),
            "source_derived_N_CRC_EW": source_derived_n_crc_ew_jsonable(
                float(self.N_CRC)
                if self.N_CRC_source == "observed_horizon_comparison"
                else DEFAULT_OBSERVED_HORIZON_N_COMPARISON
            ),
            "N_patch_bare_ratio": self.N_patch_bare_ratio,
            "Lambda_lP2": self.Lambda_lP2,
            "P_cell_count_for_N_CRC": self.P_cell_count_for_N_CRC,
            "z6_normalized_trace_mean": self.z6_normalized_trace_mean,
            "z6_reciprocal_trace": self.z6_reciprocal_trace,
            "lambda_collar": self.lambda_collar,
            "lambda_collar_exact_uniform_product_thickening": (
                self.lambda_collar_exact_uniform_product_thickening
            ),
            "lambda_collar_exact_gate": self.lambda_collar_exact_gate,
            "lambda_collar_claim_status": self.lambda_collar_claim_status,
            "lambda_collar_profile_default": self.lambda_collar_profile_default,
            "finite_thickness_jensen_band": self.finite_thickness_jensen_band,
            "reserve": self.reserve,
            "pi_wl": float(self.pi_wl),
            "epsilon_A_wl": self.epsilon_A_wl,
            "R_wl": self.R_wl,
            "oph_neutrino_mass_prediction": {
                "available": False,
                "masses_eV": None,
                "sum_mnu_eV": None,
                "public_promotion_allowed": False,
                "status": "no_source_derived_neutrino_mass_prediction",
            },
            "conventional_camb_neutrino_baseline": {
                "assumption": CONVENTIONAL_CAMB_NEUTRINO_ASSUMPTION,
                "sum_mnu_eV": float(self.conventional_camb_sum_mnu_eV),
                "counts_as_oph_prediction": False,
            },
            "N_eff": float(self.N_eff),
            "S8_oph_compressed": float(self.S8_oph_compressed),
            "S8_wl_target_reference": float(self.S8_wl_target_reference),
            "S8_wl_sigma_reference": float(self.S8_wl_sigma_reference),
            "S8_projected_wl": self.S8_projected_wl,
        }
