#!/usr/bin/env python3
"""Prepare the bounded monolithic 1,048,576-patch OPH-FPE run config."""

from __future__ import annotations

import argparse
import hashlib
import json
from copy import deepcopy
from pathlib import Path
from typing import Any

import yaml


PATCH_COUNT = 1_048_576
ACCEPTANCE_PATCH_COUNT = 4_096
PILOT_PATCH_COUNT = 65_536
PILOT_MATERIALIZED_OBSERVER_COUNT = 16_000
LARGE_PILOT_PATCH_COUNT = 131_072
LARGE_PILOT_MATERIALIZED_OBSERVER_COUNT = 32_000
MATERIALIZED_OBSERVER_COUNT = 64_000
OBSERVER_ANALYSIS_COUNT = 8_192
BASE_CONFIG = Path("configs/e4_shared_observer_bulk_256k_observers4096_theorem.yml")


def prepare_config(base: dict[str, Any], *, seed: int) -> dict[str, Any]:
    config = deepcopy(base)
    config["name"] = "e5_shared_observer_bulk_1m_bounded_visualizer"
    config["run_mode"] = "observer_shared_bulk_candidate_1m_monolithic"
    config["seed"] = int(seed)
    config["claim_boundary"] = (
        "Monolithic 1,048,576-carrier-patch diagnostic with 64,000 materialized "
        "observer-like self-reading systems sampled from the carrier: bounded patches "
        "with local state, ports/boundaries, readback, records, feedback/repair moves, "
        "and public evidence. Expensive cross-observer/H3/object lanes use one deterministic "
        "8,192-observer analysis subset, while all 64,000 local records are retained in a "
        "compact replay artifact. This is not one million materialized observer records. "
        "S2-derived geometry lanes, producerless particle contracts, and strict bulk "
        "receipts remain fail-closed. Visualization exports are deliberately capped."
        " Final-state screen fields may be exported when the BW/KMS gate fails; that lane is "
        "explicitly visualization-diagnostic and cannot promote a physical CMB or bulk claim."
    )

    config.setdefault("graph", {})["patch_count"] = PATCH_COUNT
    dynamics = config.setdefault("dynamics", {})
    dynamics["repairs_per_cycle"] = PATCH_COUNT // 16
    readback = dynamics.setdefault("observer_readback_drive", {})
    readback["max_edges_per_cycle"] = 32_768

    config["observers"] = {
        **dict(config.get("observers", {}) or {}),
        "sample_count": MATERIALIZED_OBSERVER_COUNT,
        "neighborhood_size": 160,
        "time_sample_count": 32,
        "overlap_correspondence_max_observers": OBSERVER_ANALYSIS_COUNT,
        "consensus_analysis_max_observers": OBSERVER_ANALYSIS_COUNT,
        "observer_wide_analysis_max_observers": OBSERVER_ANALYSIS_COUNT,
        "compact_unenriched_rows": True,
    }
    config["observer_consensus_readout"] = {
        "observer_sample_count": 96,
        "object_sample_count": 512,
    }
    config["visualization_export"] = {
        "max_screen_points": 3_500,
        "max_observers": 96,
        "max_h3_objects": 512,
    }
    neutral = config.setdefault("neutral_reconstruction", {})
    neutral["distance_matrix_max_observers"] = 2_048
    theorem_core = config.setdefault("theorem_core", {})
    theorem_core["include_default_sm_candidate"] = False
    theorem_core["consensus_replay"] = {
        **dict(theorem_core.get("consensus_replay", {}) or {}),
        # The exact shared-node endpoint-branch check already supplies a
        # structural nonconfluence witness. Millions of Python replay steps
        # cannot change that false C0b verdict.
        "schedule_replays": 0,
        "requested_schedule_replays": 0,
        "large_run_exact_failure_short_circuit": True,
    }

    # The organic/gravity lanes synthesize separate visual populations. They do
    # not add evidence about defects generated by the million-patch production
    # state and are disabled to keep this run scientifically focused.
    visualization_diagnostics = config.setdefault("visualization_diagnostics", {})
    visualization_diagnostics.setdefault("organic_defect_population", {})["enabled"] = False
    visualization_diagnostics.setdefault("two_defect_gravity_assay", {})["enabled"] = False

    cosmology = config.setdefault("cosmology", {})
    cosmology["harmonic_time_trace"] = {
        "enabled": True,
        "sample_count": 4,
        "ell_max": 12,
        "harmonic_batch_size": 8_192,
        "save_raw_frames": False,
        "fixed_time_controls": True,
        "controls": ["shuffled_field"],
        "fields": [
            "record_signature",
            "local_mismatch_density",
            "cumulative_repair_load",
        ],
    }
    freezeout = cosmology.setdefault("freezeout", {})
    freezeout["require_kms_bw_pass"] = False
    freezeout["million_patch_diagnostic_export_policy"] = (
        "export_final_screen_fields_for_visualization_without_promoting_bw_bulk_or_physical_cmb"
    )
    freezeout["fields"] = [
        "record_signature",
        "local_mismatch_density",
        "cumulative_repair_load",
        "s3_class_density",
    ]
    freezeout["derived_fields"] = []
    angular = cosmology.setdefault("angular_power", {})
    angular["ell_max"] = 24
    angular["pair_samples"] = 100_000
    angular["harmonic_batch_size"] = 8_192
    angular["controls"] = ["shuffled_field"]
    cmb_lite = cosmology.setdefault("cmb_lite", {})
    cmb_lite["fields"] = list(freezeout["fields"])

    # At 1M, the collar-operator lane would retain hundreds of whole-screen
    # transport maps.  The actual perturb/resettle producer is both the
    # scientifically relevant ablation and the bounded implementation.
    h3_support = config.setdefault("h3_support_profiles", {})
    h3_support["cap_count"] = 8
    h3_response = config.setdefault("h3_modular_response", {})
    h3_response.update(
        {
            "observable_mode": "perturb_resettle_transition",
            "times": [0.25],
            "candidate_count": 4_096,
            "max_fit_features": 512,
            "refine_steps": 1,
            "refine_max_rows": 24,
            "refine_max_nfev": 24,
            "max_full_graph_simulations": 32,
            "full_graph_budget_policy": "skip_if_exceeded",
            # Each worker owns one mutable million-patch probe state.  Eight
            # workers use the 64-vCPU host well without multiplying graph
            # memory by the full CPU count.
            "full_graph_n_jobs": 8,
        }
    )
    paired = cosmology.setdefault("b_a_paired_perturbation", {})
    paired.update(
        {
            "max_caps": 4,
            "modes_per_cap_time": 1,
            "a_grid": [0.01, 0.1],
            "times": [0.25],
            "max_full_graph_simulations": 24,
            "full_graph_budget_policy": "skip_if_exceeded",
            "full_graph_n_jobs": 8,
            "reuse_dynamics_across_a_grid": True,
        }
    )

    defects = config.setdefault("defects", {})
    defects["max_triangles"] = 12_000
    timeline = defects.setdefault("timeline", {})
    timeline.update(
        {
            "enabled": True,
            "sample_count": 32,
            "max_triangles": 4_096,
            "persistence_cycles": 3,
            "max_angular_speed_per_cycle": 0.75,
            "max_analysis_clusters_per_snapshot": 512,
            "max_serialized_snapshots": 32,
            "max_snapshot_clusters_per_snapshot": 512,
            "max_worldlines": 512,
            "max_events_per_worldline": 128,
            "max_support_nodes_per_record": 64,
            "max_serialized_json_bytes": 64_000_000,
        }
    )

    config["million_patch_preparation"] = {
        "schema": "oph_monolithic_million_patch_preparation_v1",
        "carrier_patch_count": PATCH_COUNT,
        "materialized_observer_count": MATERIALIZED_OBSERVER_COUNT,
        "observer_wide_analysis_count": OBSERVER_ANALYSIS_COUNT,
        "observer_wide_analysis_sampling": (
            "deterministic_observer_id_hash_rank_v1"
        ),
        "observer_population_storage": (
            "all_materialized_local_records_in_compact_npz_plus_enriched_analysis_jsonl"
        ),
        "dense_distance_observer_cap": 2_048,
        "visualizer_caps": {
            "screen_points": 3_500,
            "observers": 96,
            "h3_objects": 512,
            "raw_screen_frames": 0,
        },
        "recommended_machine": "n2-standard-64 (64 vCPU, 256 GiB)",
        "blas_threads_per_worker": 1,
        "full_graph_probe_workers": {
            "h3_modular_response": 8,
            "paired_b_a": 8,
            "execution": "bounded_ordered_thread_pool",
        },
        "full_graph_simulation_caps": {
            "h3_modular_response": 32,
            "paired_b_a": 24,
            "paired_without_a_grid_reuse": 48,
        },
    }
    validate_config(config)
    return config


def prepare_acceptance_config(base: dict[str, Any], *, seed: int) -> dict[str, Any]:
    """Derive the exact 4k launch gate from the validated production config."""

    config = prepare_config(base, seed=seed)
    config["name"] = "e5_shared_observer_bulk_4k_production_acceptance"
    config["run_mode"] = "observer_shared_bulk_candidate_1m_config_acceptance_4k"
    config["claim_boundary"] = (
        "Exact 4,096-carrier-patch acceptance gate derived from the bounded 1,048,576-patch, "
        "64,000-observer production configuration. All available 4,096 patch observers are "
        "materialized; history, analysis, probe, defect, cosmology, and visualization settings "
        "are unchanged. Passing this gate supports launch readiness only and cannot promote a "
        "bulk, particle, gravity, or physical-CMB claim."
    )
    config["graph"]["patch_count"] = ACCEPTANCE_PATCH_COUNT
    config["dynamics"]["repairs_per_cycle"] = ACCEPTANCE_PATCH_COUNT // 16
    config["million_patch_preparation"]["acceptance_gate"] = {
        "schema": "oph_monolithic_million_patch_acceptance_gate_v1",
        "production_target_patch_count": PATCH_COUNT,
        "acceptance_patch_count": ACCEPTANCE_PATCH_COUNT,
        "requested_materialized_observer_count": MATERIALIZED_OBSERVER_COUNT,
        "expected_materialized_observer_count": ACCEPTANCE_PATCH_COUNT,
        "allowed_scale_differences": [
            "name",
            "run_mode",
            "claim_boundary",
            "graph.patch_count",
            "dynamics.repairs_per_cycle",
            "million_patch_preparation.acceptance_gate",
        ],
    }
    return config


def prepare_pilot_config(base: dict[str, Any], *, seed: int) -> dict[str, Any]:
    """Derive the 64k/16k pilot without weakening production analysis gates."""

    return _prepare_scaled_pilot_config(
        base,
        seed=seed,
        patch_count=PILOT_PATCH_COUNT,
        observer_count=PILOT_MATERIALIZED_OBSERVER_COUNT,
        scale_label="64k",
    )


def prepare_large_pilot_config(base: dict[str, Any], *, seed: int) -> dict[str, Any]:
    """Derive the 128k/32k pilot without weakening production analysis gates."""

    return _prepare_scaled_pilot_config(
        base,
        seed=seed,
        patch_count=LARGE_PILOT_PATCH_COUNT,
        observer_count=LARGE_PILOT_MATERIALIZED_OBSERVER_COUNT,
        scale_label="128k",
    )


def _prepare_scaled_pilot_config(
    base: dict[str, Any],
    *,
    seed: int,
    patch_count: int,
    observer_count: int,
    scale_label: str,
) -> dict[str, Any]:
    config = prepare_config(base, seed=seed)
    config["name"] = f"e5_shared_observer_bulk_{scale_label}_observers{observer_count}_pilot"
    config["run_mode"] = f"observer_shared_bulk_candidate_1m_config_pilot_{scale_label}"
    config["claim_boundary"] = (
        f"{patch_count:,}-carrier-patch pilot derived from the bounded 1,048,576-patch production "
        f"configuration, with exactly {observer_count:,} materialized observer-like local records. The "
        "same deterministic 8,192-observer analysis cohort, 2,048 dense-geometry cap, history "
        "window, coupled probes, controls, and visualization gates are retained. This pilot "
        "cannot promote a bulk, particle, gravity, or physical-CMB claim."
    )
    config["graph"]["patch_count"] = int(patch_count)
    config["dynamics"]["repairs_per_cycle"] = int(patch_count) // 16
    config["observers"]["sample_count"] = int(observer_count)
    config["million_patch_preparation"]["pilot_gate"] = {
        "schema": "oph_monolithic_million_patch_pilot_gate_v1",
        "production_target_patch_count": PATCH_COUNT,
        "production_target_materialized_observer_count": MATERIALIZED_OBSERVER_COUNT,
        "pilot_patch_count": int(patch_count),
        "pilot_materialized_observer_count": int(observer_count),
        "observer_wide_analysis_count": OBSERVER_ANALYSIS_COUNT,
        "allowed_scale_differences": [
            "name",
            "run_mode",
            "claim_boundary",
            "graph.patch_count",
            "dynamics.repairs_per_cycle",
            "observers.sample_count",
            "million_patch_preparation.pilot_gate",
        ],
    }
    return config


def validate_config(config: dict[str, Any]) -> None:
    h3_cfg = dict(config.get("h3_modular_response", {}) or {})
    h3_scales = [
        float(h3_cfg.get("transport_scale", 2.0 * 3.141592653589793)),
        *(float(value) for value in h3_cfg.get("wrong_scales", [])),
    ]
    h3_unique_scales = list(dict.fromkeys(h3_scales))
    h3_full_graph_plan = (
        int(config.get("h3_support_profiles", {}).get("cap_count", 0))
        * len(h3_cfg.get("times", []))
        * len(h3_unique_scales)
    )
    paired_cfg = dict(
        config.get("cosmology", {}).get("b_a_paired_perturbation", {}) or {}
    )
    analytic_controls = {
        "no_perturbation",
        "no_repair_load_channel",
        "baryon_delta_applied_after_record_freezeout",
    }
    live_paired_controls = sum(
        str(value) not in analytic_controls for value in paired_cfg.get("controls", [])
    )
    paired_full_graph_plan = (
        2
        * int(paired_cfg.get("max_caps", 0))
        * len(paired_cfg.get("times", []))
        * max(1, int(paired_cfg.get("modes_per_cap_time", 1)))
        * (1 + live_paired_controls)
    )
    checks = {
        "patch_count": config.get("graph", {}).get("patch_count") == PATCH_COUNT,
        "repair_budget": config.get("dynamics", {}).get("repairs_per_cycle") == PATCH_COUNT // 16,
        "history_window": int(config.get("bw", {}).get("history_window", 0)) >= 32,
        "materialized_observers": int(
            config.get("observers", {}).get("sample_count", 0)
        )
        == MATERIALIZED_OBSERVER_COUNT,
        "observer_wide_analysis_cap": int(
            config.get("observers", {}).get(
                "observer_wide_analysis_max_observers", 0
            )
        )
        == OBSERVER_ANALYSIS_COUNT
        and int(
            config.get("observers", {}).get(
                "overlap_correspondence_max_observers", 0
            )
        )
        == OBSERVER_ANALYSIS_COUNT
        and int(
            config.get("observers", {}).get(
                "consensus_analysis_max_observers", 0
            )
        )
        == OBSERVER_ANALYSIS_COUNT
        and config.get("observers", {}).get("compact_unenriched_rows") is True,
        "dense_distance_cap": int(
            config.get("neutral_reconstruction", {}).get("distance_matrix_max_observers", 0)
        )
        <= 2_048,
        "screen_export_cap": int(config.get("visualization_export", {}).get("max_screen_points", 0))
        <= 3_500,
        "observer_export_cap": int(config.get("visualization_export", {}).get("max_observers", 0))
        <= 96,
        "object_export_cap": int(config.get("visualization_export", {}).get("max_h3_objects", 0))
        <= 512,
        "raw_frames_disabled": config.get("cosmology", {})
        .get("harmonic_time_trace", {})
        .get("save_raw_frames")
        is False,
        "harmonic_trace_bounded": int(
            config.get("cosmology", {})
            .get("harmonic_time_trace", {})
            .get("sample_count", 0)
        )
        <= 4
        and int(
            config.get("cosmology", {})
            .get("harmonic_time_trace", {})
            .get("ell_max", 0)
        )
        <= 12,
        "freezeout_harmonics_bounded": int(
            config.get("cosmology", {}).get("angular_power", {}).get("ell_max", 0)
        )
        <= 24
        and len(
            config.get("cosmology", {}).get("freezeout", {}).get("fields", [])
        )
        <= 4,
        "diagnostic_freezeout_export_enabled": config.get("cosmology", {})
        .get("freezeout", {})
        .get("require_kms_bw_pass")
        is False
        and config.get("cosmology", {})
        .get("freezeout", {})
        .get("million_patch_diagnostic_export_policy")
        == "export_final_screen_fields_for_visualization_without_promoting_bw_bulk_or_physical_cmb",
        "perturb_resettle_h3_lane": config.get("h3_modular_response", {}).get(
            "observable_mode"
        )
        == "perturb_resettle_transition"
        and int(config.get("h3_support_profiles", {}).get("cap_count", 0)) <= 8
        and int(
            config.get("h3_modular_response", {}).get(
                "max_full_graph_simulations", 0
            )
        )
        <= 32
        and 0 < int(h3_cfg.get("full_graph_n_jobs", 0)) <= 8
        and h3_full_graph_plan
        <= int(h3_cfg.get("max_full_graph_simulations", 0)),
        "paired_probe_grid_bounded": int(
            config.get("cosmology", {})
            .get("b_a_paired_perturbation", {})
            .get("max_caps", 0)
        )
        <= 4
        and int(
            config.get("cosmology", {})
            .get("b_a_paired_perturbation", {})
            .get("modes_per_cap_time", 0)
        )
        <= 1
        and len(
            config.get("cosmology", {})
            .get("b_a_paired_perturbation", {})
            .get("a_grid", [])
        )
        <= 2
        and int(
            config.get("cosmology", {})
            .get("b_a_paired_perturbation", {})
            .get("max_full_graph_simulations", 0)
        )
        <= 24
        and 0 < int(paired_cfg.get("full_graph_n_jobs", 0)) <= 8
        and bool(
            config.get("cosmology", {})
            .get("b_a_paired_perturbation", {})
            .get("reuse_dynamics_across_a_grid", False)
        )
        and paired_full_graph_plan
        <= int(paired_cfg.get("max_full_graph_simulations", 0)),
        "consensus_exact_failure_short_circuit": config.get("theorem_core", {})
        .get("consensus_replay", {})
        .get("large_run_exact_failure_short_circuit")
        is True
        and int(
            config.get("theorem_core", {})
            .get("consensus_replay", {})
            .get("schedule_replays", -1)
        )
        == 0
        and int(
            config.get("theorem_core", {})
            .get("consensus_replay", {})
            .get("requested_schedule_replays", -1)
        )
        == 0,
        "defect_assignment_cap": 0
        < int(
            config.get("defects", {})
            .get("timeline", {})
            .get("max_analysis_clusters_per_snapshot", 0)
        )
        <= 512,
        "defect_snapshot_cap": 0
        < int(
            config.get("defects", {})
            .get("timeline", {})
            .get("max_serialized_snapshots", 0)
        )
        <= 32,
        "defect_json_hard_cap": 0
        < int(
            config.get("defects", {})
            .get("timeline", {})
            .get("max_serialized_json_bytes", 0)
        )
        <= 64_000_000,
    }
    failed = [name for name, passed in checks.items() if not passed]
    if failed:
        raise ValueError("unsafe million-patch config: " + ", ".join(failed))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", type=Path, default=BASE_CONFIG)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--seed", type=int, default=20_260_753)
    scale = parser.add_mutually_exclusive_group()
    scale.add_argument(
        "--acceptance-4k",
        action="store_true",
        help="derive the exact 4,096-patch preflight from the validated 1M config",
    )
    scale.add_argument(
        "--pilot-64k-16k",
        action="store_true",
        help="derive the 65,536-patch/16,000-observer pilot from the 1M config",
    )
    scale.add_argument(
        "--pilot-128k-32k",
        action="store_true",
        help="derive the 131,072-patch/32,000-observer pilot from the 1M config",
    )
    args = parser.parse_args()

    base_bytes = args.base.read_bytes()
    base = yaml.safe_load(base_bytes)
    if not isinstance(base, dict):
        raise ValueError("base config must be a YAML mapping")
    if args.acceptance_4k:
        config = prepare_acceptance_config(base, seed=args.seed)
    elif args.pilot_64k_16k:
        config = prepare_pilot_config(base, seed=args.seed)
    elif args.pilot_128k_32k:
        config = prepare_large_pilot_config(base, seed=args.seed)
    else:
        config = prepare_config(base, seed=args.seed)
    config["million_patch_preparation"]["base_config"] = str(args.base)
    config["million_patch_preparation"]["base_config_sha256"] = (
        "sha256:" + hashlib.sha256(base_bytes).hexdigest()
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
    print(
        json.dumps(
            {
                "config": str(args.out),
                "patch_count": int(config["graph"]["patch_count"]),
                "requested_materialized_observers": int(
                    config["observers"]["sample_count"]
                ),
                "expected_materialized_observers": min(
                    int(config["observers"]["sample_count"]),
                    int(config["graph"]["patch_count"]),
                ),
                "observer_wide_analysis_count": OBSERVER_ANALYSIS_COUNT,
                "dense_distance_observer_cap": 2_048,
                "visualizer_caps": config["million_patch_preparation"]["visualizer_caps"],
                "full_graph_simulation_caps": config["million_patch_preparation"][
                    "full_graph_simulation_caps"
                ],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
